### ISSUE TITLE
Add Twemoji 2.0 assets

### ISSUE THREAD

**Issue by samantha-cruz** [twitter/twemoji#103]
Hi, when will the new emoji assets be added to this repo? Thansk

**Comment by bhaggs** [comment]
Yesterday (12/9/15) we deployed the Twemoji 2.0 assets to Twitter.com. We're actively working on getting it all wrapped up to be pushed to github. So soon it'll be up here.

**Comment by samantha-cruz** [comment]
thanks @bhaggs looking forward to it. :smile:

**Comment by jk779** [comment]
Can't wait!! 🙏

**Comment by thekondrashov** [comment]
+1

**Comment by txtsd** [comment]
Can't wait to use this to rebuild my custom Twemoji font!

**Comment by jerrygrey** [comment]
@bhaggs can we get a ETA?

**Comment by rikimaru1** [comment]
@txtsd Can you share your current font, sir?

**Comment by txtsd** [comment]
@rikimaru1 I don't think it's what you're looking for. It uses Twemoji, but falls back to Emoji One > Noto > iOS9. If you're looking for a consistent experience, it's a terrible choice of emoji fonts.

**Comment by rikimaru1** [comment]
Jesuschrist, merge 2.0 once for all

**Comment by rikimaru1** [comment]
I think this is taking too long just for some png's.

**Comment by jerrygrey** [comment]
@bhaggs can we have an update on this please?

**Comment by Viperusgit** [comment]
here is the 72x72 assets for Twemoji 2.0 https://goo.gl/X07kCg I feel like these should just be uploaded to GitHub already but whatever

**Comment by Viperusgit** [comment]
Read this post on XDA for the assets http://forum.xda-developers.com/showthread.php?p=64596102 I feel like these assets should just be pushed already!

**Comment by rikimaru1** [comment]
@Viperusgit I uploaded that zip, man, sadly it doesn't mean assets will be uploaded soon.

**Comment by zubinmehta** [comment]
+1

**Comment by bhaggs** [comment]
We're currently cleaning up all the SVGs (approximately over 1,500 files) to get them ready to be pushed. The PNG assets are predominantly done but we're going to release them together with the finalized SVGs.

**Comment by dmcveigh** [comment]
@bhaggs can we have please an ETA on this release?

**Comment by tln** [comment]
Awesome news, is there ay update on this? Anything the community can do to help @bhaggs ?

**Comment by rikimaru1** [comment]
If you all want an advice, switch to Emoji One 2.0. They look a pretty decent company, they take their users seriously. Plus they released 8.0 assets more than 1 month ago.

This is a joke compared to them.

**Comment by jerrygrey** [comment]
@rikimaru1 Twemoji looks much better though

**Comment by WebReflection** [comment]
@rikimaru1 we have a code of conduct here so please try to not insult anyone, like saying nobody cares about users, thank you.

For what I can tell, and I am an external volunteer here 'cause I don't work at Twitter anymore and I'm maintaining only the JS side of this project, there is interest from the company to keep improving this project but it's pretty clear the main Twitter goal right now is not Twemoji.

However, someone officially replied already saying assets are coming and I'm pretty sure if for a couple of months these won't be out nothing that bad could happen in this world, isn't it?

That being said, since I'm also completely unaware of anything happening because I'm not part of any official communication channel, if by the end of February (luckily 29 days this year!) there won't be any update, I'm going to fork this and accept assets from anyone around this world so we'll drop the suspense and move the Web forward.

Best Regards

**Comment by Viperusgit** [comment]
@rikimaru1 good news you can get the font file from a forum on XDA (the same place you posted the assets zip on)

**Comment by jerrygrey** [comment]
@WebReflection Hopefully that doesn't happen, but if it does, I can help out with the SVG files.

**Comment by WebReflection** [comment]
thanks @jerrygrey ... it will eventually be SVG only and no closed software involved at all for sure so thanks again.

**Comment by jerrygrey** [comment]
@WebReflection That's good, I was worried it would go PNG only 👍

**Comment by WebReflection** [comment]
eheh ... you can always get a PNG from an SVG at any resolution ... not vice-versa so ... easy to guess the assets requirement ;-)

**Comment by WebReflection** [comment]
[V2 has landed](https://github.com/twitter/twemoji#unicode-80-and-diversity) with 1661 emoji coevered VS just 874 in previous version.

Easy way to update? prefix `/twemoji.min.js` from MaxCDN via `2/twemoji.min.js` and you're good to go.

**Comment by thekondrashov** [comment]
@WebReflection Wow, that's awesome work! Thank you.
