### ISSUE TITLE
List of Twemoji names?

### ISSUE THREAD

**Issue by JuanitoFatas** [twitter/twemoji#108]
Hello there!

In Twemoji, we use `:thumbsup:` instead of `:+1:` for U+1F44D (:+1:).

Is there a list of Twemoji names file somewhere?

Thanks!

**Comment by WebReflection** [comment]
here we don't actually use emoji nick-names or shortcut at all. The code size would grow quite a lot if we were. Names are also defined by Unicode consortium. Accordingly I would personally not recommend shortcuts unless universally accepted (defined at Unicode level)

**Comment by JuanitoFatas** [comment]
Accordingly I would personally not recommend shortcuts unless universally accepted (defined at Unicode level)

:+1: 

I found Unicode has [emoji annotations](http://www.unicode.org/emoji/charts/emoji-annotations.html).

--

These nicknames are handy to implement autocomplete for users.

**Comment by JuanitoFatas** [comment]
Sorry, because twemoji-awesome [uses `thumbsup` as name for thumbs up]((https://github.com/ellekasai/twemoji-awesome/blob/49b6fe6/twemoji-awesome.css#L310)), I thought it got the data from twitter/twemoji, but actually it got the data from [emoji-cheatsheet](https://github.com/arvida/emoji-cheat-sheet.com/).

Close this.

**Comment by WebReflection** [comment]
Users don't autocomplete emoji, they pick them from the phone/tablet virtual keyboard or they should have a way to pick them graphically.

Writing them  directly is somehow simulating old BB Code and forums style. It works if you have unique identifier and you don't mispell it, it doesn't work if you don't have a universally agreed standard that identify them uniquely.

The unicode page shows "groups" and not unique identifiers, but IIRC there is a list if unique identifiers and descriptions per char. I'd personally recommend that so that people that need to type them instead of selecting them  graphically (let's say people that cannot select them visibly on a textarea) should know one and one only  way to show an emoji through a single identifier.

That Unicode page as example accepts bot `+1` and `thumbs up` and so should  do any textearea that converts special  cases into emoji.

Best Regards

**Comment by dessalines** [comment]
I really need a full list of the aliases / shortcodes for a mentions library. Does anyone know where this exists?

**Comment by WebReflection** [comment]
if you visit https://unicode.org/emoji/charts/full-emoji-list.html and you write the following in the console:

```js
(function () {
  const script = document.createElement('script');
  script.onload = () => {
    const emoji = {};
    for (const code of document.querySelectorAll('td.code')) {
      let key = '';
      code.textContent.trim().split(' ').forEach(unicode => {
        key += twemoji.convert.fromCodePoint(unicode.replace('U+', ''));
      });
      emoji[key] = code.parentElement.lastElementChild.textContent.trim();
    }
    window.emoji = emoji;
  };
  document.head.appendChild(script).src =
    'https://twemoji.maxcdn.com/v/latest/twemoji.min.js';
}());
```

you'll create an object with emoji => description info (as in key/value) but for thing like `:thumb_up:` you need a convention with the description (i.e. use `_` instead of space).

As example, the following code would create a similar object with code to desc and desc to code:

```js
(function () {
  const script = document.createElement('script');
  script.onload = () => {
    const emoji = {};
    for (const code of document.querySelectorAll('td.code')) {
      const desc = underscored(code.parentElement.lastElementChild.textContent);
      let key = '';
      code.textContent.trim().split(' ').forEach(unicode => {
        key += twemoji.convert.fromCodePoint(unicode.replace('U+', ''));
      });
      emoji[key] = desc;
      emoji[desc] = key;
    }
    window.emoji = emoji;
  };
  document.head.appendChild(script).src =
    'https://twemoji.maxcdn.com/v/latest/twemoji.min.js';
  function underscored(desc) {
    return desc.trim().replace(/[ :]+/g, '_');
  }
}());
```

If you want to save such info somewhere, just `JSON.stringify(emoji, null, '  ')` and that should be it.

**Comment by dessalines** [comment]
Finally got this working, thank you so much @WebReflection !

**Comment by WebReflection** [comment]
@dessalines I've created an npm package that contains only the dictionary: https://github.com/WebReflection/emoji-short-name

The dictionary is created directly from unicode.org site, and through `String.fromCodePoint` mechanism, granting best reliability and weighting the least amount of bytes.

From that module, you can create as many alternatives you want, as long as the size is contained (already ~50K of data itself).

I hope this better suits your needs, so that there is an automation in place able to do what I've previously described in here, so that no error, or misunderstanding, is possible, and we also don't need to bother uniode.org bandwidth too much (that's a very heavy page).

Best Regards

**Comment by jpeggdev** [comment]
I used this json file to help me create a local lookup table in my database.

https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji.json
