### ISSUE TITLE
Description of the emoji in the tooltip

### ISSUE THREAD

**Issue by jerrygrey** [twitter/twemoji#132]
I think it would be useful if the description of the emoji in put in the "title" attribute so it will appear as a tooltip when hovering, like "face with stuck-out tongue and winking eye". This will help explain the emoji when it is not clear exactly what it is off the bat. This happens on Twitter already.

What did you guys think?

**Comment by WebReflection** [comment]
on twitter there's no overhead because it's rendered on the server. On twemoji it would be an overhead of 1600+ text making the library not suitable anymore for mobile and paying data-roaming customers.

It might be a good idea to provide a file a part that could also be somehow plugged-in on demand and let users make this choice but so far it hasn't been needed much and it won't bring any benefit on mobile where there's no hover.

A "to thnik about" but not a bug.

**Comment by WebReflection** [comment]
side note: also .. translations ... for i18n delivery ... I don't see this happening that soon but worth considering

**Comment by jerrygrey** [comment]
I actually don't use the JS files included, I convert the emoji server-side, so a list would be quite useful for me and I'm sure others would find it useful too.

**Comment by WebReflection** [comment]
then you have the Unicode consortium which provides such list already. Twemoji is the JS library on top of Twitter's emoji assets. If you don't need JS you can use assets to obtain what you need ;-)
