### ISSUE TITLE
Twemoji keywords data

### ISSUE THREAD

**Issue by JuanitoFatas** [twitter/twemoji#147]
Hello 👋 

During the upgrade of [twemoji RubyGem](https://github.com/jollygoodcode/twemoji) to support twemoji.js V2. We open sourced the keyword to unicode mapping data (e.g. `:heart: => U+2764`), available in json and yaml format:

- twemoji.js V1 [yaml](https://github.com/jollygoodcode/emoji-keywords/blob/master/twemoji/v1/keywords.yaml) [json](https://github.com/jollygoodcode/emoji-keywords/blob/master/twemoji/v1/keywords.json)
- twemoji.js V2 [yaml](https://github.com/jollygoodcode/emoji-keywords/blob/master/twemoji/v2/keywords.yaml) [json](https://github.com/jollygoodcode/emoji-keywords/blob/master/twemoji/v2/keywords.json)

Will twemoji consider provide an offical list of keywords based on these? Thanks!

**Comment by WebReflection** [comment]
not sure I understand why you'd like to have this in twemoji.

user writes, server parse and store text doing that keyword to unicode conversion, twemoji will render later on such unicode char.

I feel like I'm missing something.

**Comment by JuanitoFatas** [comment]
> why you'd like to have this in twemoji.

For web applications, it is popular that people would type `:heart:` instead of the unicode `❤` on a textarea (like the GitHub comment we are using):

<img width="203" alt="screenshot 2016-06-13 13 52 17" src="https://cloud.githubusercontent.com/assets/1000669/15998105/0e1adff2-316e-11e6-8735-d545a29346e2.png">

Or on Slack:

<img width="635" alt="screenshot 2016-06-13 13 53 50" src="https://cloud.githubusercontent.com/assets/1000669/15998132/4633a0f4-316e-11e6-9e68-c03000d4c050.png">

[discourse maintains a list of name to unicode mapping by thereselves](https://github.com/discourse/discourse/blob/master/lib/emoji/db.json), GitHub provides [this kind of data](https://api.github.com/emojis), and others like [emojicodes](http://emoji.codes/), and [emoji-cheat-sheet](emoji-cheat-sheet.com).

Would be great if Twitter can officially provides these data too.

**Comment by WebReflection** [comment]
emojicodes looks like based on twemoji as well, those emoji loo kway too familiar.

That's why I don't understand what you need. There are others providing that mapping and here we're not implementing any UI for textareas.

It's about giving you a transformer ability for standard unicode chars.

It looks like you'd like to have twemoji parsing those "codes" instead of unicode standards but people on mobile would never do that, they'll simply chose the emoji from their native keyboard.

People on Web might do that, but I think is out of twemoji scope to provide something that doesn't come from Unicode consortium.

Moreover, I think is out of scope to bring here the work others did in their own repositories.

If you are thinking about generating a regexp with those words and map parsing at runtime I'm still a bit skeptic it's a twemoji responsibility.

GitHub, as example, can show whatever they want then put an image or put on the area the unicode char eventually parsed via twemoji.

I think these projects should complement each other, not replace. Does this answer your question?
