### ISSUE TITLE
Adding the new Power Symbols

### ISSUE THREAD

**Issue by edent** [twitter/twemoji#161]
Unicode 9 adds 5 characters to the Misc Technical block which I believe would be excellent candidates for Twemoji.

What's the best way to add these characters?  Just a PR with the SVG - or do I need to include all PNG variants?

<table class="box-table">
<thead>
<tr>
<th>Character</th>
<th>Escape Code</th>
<th>Symbol</th>
</tr>
</thead>
<tr>
<td>Power</td>
<td>&amp;#x23FB;</td>
<td><span class="iec_power">&#x23FB;</span>
</td>
</tr>
<tr>
<td>Toggle Power</td>
<td>&amp;#x23FC;</td>
<td><span class="iec_power">&#x23FC;</span></td>
</tr>
<tr>
<td>Power On</td>
<td>&amp;#x23FD;</td>
<td><span class="iec_power">&#x23FD;</span></td>
</tr>
<tr>
<td>Power Off</td>
<td>&amp;#x2B58;</td>
<td><span class="iec_power">&#x2B58;</span></td>
</tr>
<tr>
<td>Sleep Mode</td>
<td>&amp;#x23FE;</td>
<td><span class="iec_power">&#x23FE;</span></td>
</tr>
</table>

Full details of the symbols are at http://unicodepowersymbol.com/

**Comment by bhaggs** [comment]
It doesn't seem that the unicode 9.0 spec defines that these characters should have an emoji variant, only a text style display. So I'm not sure they would make good candidates to be included in the emoji set.

**Comment by Crissov** [comment]
That’s partially right as far as I know. Unicode 9 indeed does not say that these characters *should* have an emoji variant, but it also doesn’t say that they *must not* have one (i.e. “only a text style display”). If an emoji font like Twemoji wants to include them it is free to do so, but since these codepoints have no variation sequences with VS15 and VS16 (U+FE0E/F) defined in [StandardizedVariants.txt](http://unicode.org/Public/UCD/latest/ucd/StandardizedVariants.txt) the variation selectors must have no effect on them.

**Comment by bhaggs** [comment]
I would recommend submitting a proposal to the Unicode Emoji Subcommittee.
