### ISSUE TITLE
v2.0.5 does not actually improve npm.

### ISSUE THREAD

**Issue by jhgg** [twitter/twemoji#167]
Some people (including ourselves) use the svg assets distributed in the NPM package to be `require`'d in our webpack bundle - as opposed to using the twemoji CDN to host emoji. 

We've forked this repo for now and un-ignored these assets, but wondering the rationale behind a breaking change like this passed as a patch version update.

**Comment by WebReflection** [comment]
version 2 brought consistent changes to the folders structure so that assets are not anymore on the root of the package.

Since all assets have been historically ignored, I actually thought it was by accident that SVGs were included in the `npm` package, also because with the `bower` one somebody previously complained about assets that were making installation painfully slow.

However, I agree this could've have been a breaking change.

Would `./2/svg` inclusion be a valuable change? The `./svg` points at the `V1` version of twemoji, not the latest which is `V2`, and the `npm` version 2 should be about `V2` meaning if you need `V1` assets, the `svg` folder you were using before, you need to use a version `1` of this library.

**Comment by jhgg** [comment]
Yeah. We just use ./2/svg/. Everything else we can render from the vectors

**Comment by WebReflection** [comment]
something weird is happening ... I've dropped the folder from npmignore:
https://github.com/twitter/twemoji/commit/b3c6f9635da169dbaf90279e5eaf67228c694b49

And [bumped](https://github.com/twitter/twemoji/commit/6d3f48db80ae87748839cd12f517f601afdfa6bd) the version [twice](https://github.com/twitter/twemoji/commit/1034eea6f471f0e3eae61f086ebb1c41e3d48f67) and published with 2 different versions of `npm` but assets don't seem to be pushed to the `npm` package.

I'll try to find time to better investigate what's going on. If you have any clue, please share. Thanks.

**Comment by jhgg** [comment]
Hi - that is definitely strange! Here is the diff that fixed it for us: https://github.com/hammerandchisel/twemoji/commit/ccff6ea5df71963ba32a8576899aac563afc2a36

**Comment by jhgg** [comment]
I think that it's because you have `svg` on line 9 instead of `/svg` which ignores all folders named "svg"

**Comment by WebReflection** [comment]
Good catch, fixed now. Thanks.
