### ISSUE TITLE
Provide Opentype fonts

### ISSUE THREAD

**Issue by Crissov** [twitter/twemoji#176]
Since you already generate SVG and PNG files from the AI sources, it should be rather simple to automatically make font files using Adobe’s/Mozilla’s SVGinOTF approach or Google’s standardized (and Apple’s proprietary) PNGinOTF approach. The Microsoft variant may be a bit more complicated, because it requires conversion of the graphics to TTF glyph outlines.

I know that some operating systems only support custom emoji fonts if they have a certain file name or font name or both.

**Comment by WebReflection** [comment]
> it should be rather simple to ...

PRs are always welcome.

However, this has been previously discussed and it turned out, not only is not "_rather simple_", it's also outside this repository scope.

Please check external projects that use these assets:
https://github.com/twitter/twemoji#community-projects

One of them maybe already solve your problem:
https://github.com/eosrei/twemoji-color-font

**Comment by Crissov** [comment]
Sorry, I should have seen the community project by @eosrei – since that exists it’s indeed “rather simple”. I believe my confusion is best explained by the scope of this project: I thought it was primarily about developing the graphics (which are shared with related projects), but I now realize it’s actually more about the JS framework and that also explains #175. Maybe the graphics should live in a separate repository – Emojidex even separates [PNGs](https://github.com/emojidex/emojidex-rasters) from [SVGs](https://github.com/emojidex/emojidex-vectors). The [Emojione project](https://github.com/Ranks/emojione), for comparison, separates graphics (incl. fonts) and code with `/assets` and `/lib` folders.

**Comment by eosrei** [comment]
On the contrary, haha, I've got at least 200hrs (unpaid) in the two emoji fonts (twemoji/emojione) and the font build system I had to write to make them. Definitely not "rather simple" 😉😋

**Comment by WebReflection** [comment]
FWIW @eosrei, 99% of my contribution here is also unpaid since I've left Twitter few days after this project got officially announced.

It's "_rather simple_" to come here and complain about everything though; luckily people that appreciate our effort exceed others.

So, @eosrei, thanks a lot for your contribution!

**Comment by Crissov** [comment]
Don’t get me wrong, I do appreciate your efforts, having donated thousands of unpaid hours to not-for-profit projects myself, though only a small part of that in coding and design. I usually hate it, too, if people assume something was quick and easy to achieve, because it looks simple from the outside. 

What I actually meant with “it should be rather simple to automatically make font files …” was that I expected there was already a standard tool chain for that task (but not for SVG to `glyf` conversion). Someone had to build that first, of course, and that’s what @eosrei seems to have done successfully, but now that it does exist, isn’t any future SVG/PNG emojis into OTF operation “rather simple” in fact? Honestly, I thought, some of the vendors who proposed the different color glyphs in OTF technologies would also have provided the necessary tools to promote the(ir) solution.
