### ISSUE TITLE
Handshake skin variations emoji are missing

### ISSUE THREAD

**Issue by madgnome** [twitter/twemoji#192]
The handshake emoji (`1f91d`) is present https://twemoji.maxcdn.com/2/72x72/1f91d.png

but the different skin variations are missing:

- https://twemoji.maxcdn.com/2/72x72/1f91d-1f3fb.png
- https://twemoji.maxcdn.com/2/72x72/1f91d-1f3fc.png
- https://twemoji.maxcdn.com/2/72x72/1f91d-1f3fd.png
- https://twemoji.maxcdn.com/2/72x72/1f91d-1f3fe.png
- https://twemoji.maxcdn.com/2/72x72/1f91d-1f3ff.png

**Comment by Crissov** [comment]
Handshake has been removed from drafts of UTR#51 before Emoji 4.0 was [released](http://www.unicode.org/emoji/charts/emoji-released.html) earlier this week, because there was no way to select individual colors for each hand. Emojione may still support U+1F91D as a base for the Fitzpatrick modifiers U+1F3Fx, but it doesn’t have to.

**Comment by bhaggs** [comment]
Yup, we've removed these based on recent changes which UNICODE has ratified as @Crissov mentioned.

**Comment by Nektro** [comment]
Why not have it accept two modifiers:  
So 1f91d-1f3fb would have both hands be type 1  
and 1f91d-1f3fb-1f3fc would have the left be type 1 and the right be type 2?

**Comment by pento** [comment]
In order to select individual colours for each person in the multi-person emoji, it would require an unmaintainable number of extra images. There are currently:

- 11 emoji with 2 people (including handshake)
- 12 emoji with 3 people
- 9 emoji with 4 people

With 5 skin tones, plus the default yellow, there would need to be `11 × 6² + 12 × 6³ + 9 × 6⁴ = 14652` images, instead of the current 32. For comparison, Twemoji currently has 2661 images.

On top of that, I don't think there'd be any user friendly way for an emoji keyboard to allow specifying the skin tone for each person in a group.

And so, with the option of only allowing family groups of a single skin tone being obviously unacceptable, the reasonable option was to drop skin tone modifiers for multi-person emoji.

**Comment by Nektro** [comment]
U+1F91D is the handshake emoji with only two hands. Implementations would only need `6^2 = 36` glyphs. The family combinations were not in the scope of this issue.

**Comment by pento** [comment]
Family combinations were in the scope of why multi-person emoji (including handshake) don't have skin tone options: http://www.unicode.org/L2/L2016/16332-remove-multi-emb.pdf

Twemoji implements the Unicode emoji standard, so adding skin tone combinations to handshake (and not to family combinations) would need to be approved by the Unicode Consortium.

**Comment by Nektro** [comment]
Oh. Sorry about that :)

**Comment by Crissov** [comment]
Actually, Twemoji would be free to support additional skin color combinations for groups/families, like Microsoft does, but that would require a lot of PNG bitmap files, as explained by @pento, and some new workflows for SVGs. This would work because these emojis are the result of a sequence of multiple base emojis each of which can have a skin tone modifier attached to it, whereas Handshake is a single character and UTS#51 would indeed have to sanction multiple modifiers first to ensure compatibility (e.g. right vs. left and top vs. bottom first).
