### ISSUE TITLE
String with double \ not supported

### ISSUE THREAD

**Issue by yash3492** [twitter/twemoji#206]
Hi,
I am trying to show emoji from string like `Hey \ud83d\udc4d, How are you...`.
which is internally stored as `Hey \\ud83d\\udc4d, How are you...`. So string with double slash is not working.

I think internally javascript store a string with single slash as double slash string (escaping), which is not working with twemoji.

Basically for me
```
// This works

var yash = "\ud83d\udc4d";
twemoji.parse(yash);



// But this does not

var sandeep = "\\ud83d\\udc4d";
console.log(sandeep);
// prints \ud83d\udc4d
twemoji.parse(sandeep);
```

Any help will be helpful.

Thanks

**Comment by WebReflection** [comment]
This is a code point pair:
```js
var yash = "\ud83d\udc4d";
```

While this, is a string with 12 chars:
```js
var yash = "\\ud83d\\udc4d";
```

List of chars being: `\\`, `u`, `d`, `8`, `3`, `d`, `\\`, `u`, `d`, `c`, `4`, `d`


> I am trying to show emoji from string ... internally stored as Hey \\ud83d\\udc4d, How are you.... So 

This has nothing to do with how JavaScript works. This is you storing escaped strings.

If you replace all `\\` as `\\\\` in, you need to replace all `\\\\` as `\\` out and at once.

```js
// save
strore(str.replace(/\\/g, '\\\\'));

// retrieve
unstore(str.replace(/\\\\/g, '\\'));
```

However, you should ask yourself why you store escaped slashes in the first place since that ain't needed at all, it's just standard strings as specified in ECMAScript, twemoji has nothing to do with that.

**Comment by yash3492** [comment]
Although saving mechanism does not have such escaping, but i will double check it.

Thanks for the help.

**Comment by WebReflection** [comment]
I don't know where or how you store those strings

If you have `var yash = "\ud83d\udc4d";` in JS and you do `localStorage.setItem('yash', yash)` as example, you'll have that point pairs back as you stored it so that `"\ud83d\udc4d" === localStorage.getItem('yash');`
