### ISSUE TITLE
Emoji Parses the 'alt' attribute again and replaces it with second image on render.

### ISSUE THREAD

**Issue by anuragdamle** [twitter/twemoji#208]
Emoji Parses the 'alt' attribute again and replaces it with second image on seond-render. Can we somehow ignore the alt tag while giving a html input to twemoji.parse?

**Comment by WebReflection** [comment]
can you please provide a test to validate this bug?

**Comment by OlivierJaquemet** [comment]
Indeed, the string parsing is not reentrant and invoking it twice will lead to invalid HTML. 

    var htmlString = 'Some <string>HTML</strong>string, with an emoji : \u2764';
    htmlString = twemoji.parse(htmlString);
    < "Some <string>HTML</strong>string, with an emoji : <img class="emoji" draggable="false" alt="❤" src="https://twemoji.maxcdn.com/2/72x72/2764.png">"

Invoking method a second times breaks the HTML :

    htmlString = twemoji.parse(htmlString);
    < "Some <string>HTML</strong>string, with an emoji : <img class="emoji" draggable="false" alt="<img class="emoji" draggable="false" alt="❤" src="https://twemoji.maxcdn.com/2/72x72/2764.png">" src="https://twemoji.maxcdn.com/2/72x72/2764.png">"

Not that I would recommend it, but if you really need a workaround. And provided you don't care about cross browser compatibility, you could use the `DOMParser` API to implement a reentrant string parsing method : 

    // Reentrant string parsing, 
    // Warning : implementation not cross browser, without error handling, may not be secured, and not validated
    var twemojiParse = function(htmlString, options) {
      var domParser = new DOMParser();
      var doc = domParser.parseFromString(htmlString, "text/html");
      var parsedBody = twemoji.parse(doc.body, options)
      htmlString = parsedBody.innerHTML;
      return htmlString;
    }

Then doing this is perfectly fine : 
    twemojiParse(twemojiParse(twemojiParse(htmlString)))

MDN suggest a polyfill implementation of this API : 
https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

**Comment by WebReflection** [comment]
So, this bug is like saying that encoding html twice an `&` char will produce `&amp;amp;` which is expected.

Do not parse strings twice or use the DOM parser to be sure images are not touched.

The string parser is fast and simple, nobody had issues in the last 4+ years with it and anyone can slow down multiple parse of the same string through your technique so I don't think we need to add complexity, increase size, and risk compatibility issues, requiring a polyfill, for something that is fundamentally a mistake from the user that should never use twice any string encoder of any kind, including twemoji when it comes to text instead of DOM nodes.

Thanks for the work around though, maybe someone would prefer that way so it's good to have it here.
