### ISSUE TITLE
global is undefined

### ISSUE THREAD

**Issue by linuxqna** [twitter/twemoji#218]
I'm getting `global is undefined` error on browser.
https://github.com/twitter/twemoji/blob/gh-pages/2/twemoji.npm.js#L1

Can you do 
```javascript
var location = global && global.location || {};
```

**Comment by WebReflection** [comment]
that's nothow JS works. If something is not defined it throws.
If you use the CommonJS, NodeJS, npm version of the library, you better be sure your environment is compatible with it.

otherwise, feel free to use any CDN version of this project

**Comment by irae** [comment]
I think the original commenter is correct in this being a bug, but maybe a longer explanation is needed.

Please, note that I could just PR a fix for this, but instead I prefer to give the maintainers a bit more context and leave the decision making for you, since this is likely a 1 line fix, and understanding the reason is more valuable than the fix itself. (I'll probably PR later if I have the time)

Since `global` is not part of Javascript itself, but a NodeJS runtime specific implementation, if `twemoji` has any intention of supporting browsers, I think you might want to improve the packaging process by avoiding it's use. That said, if you take a look at the code and at your `npm` package you will notice some things that look amiss:

  1. `twemoji` clearly cares about browser, there are published UMD and minified versions provided
  2. Tweemoji is aware of build steps, since it packages separately for the browser and for `npm`.
  3. `global` is only used to get `global.location`, which BTW is not part of the NodeJS runtime. So I would say code semantics are slightly wrong.

It looks to me, this is easily fixable by changing your code to look for Window. Something like this should work:

`var location = typeof window !== 'undefined' ? window.location : {};`

Another way to fix, would be to compile a browser version that replaces `global` in your code by `window`. You can safely do this, if you add `{"main": "./2/twemoji.npm.js", "browser": "./2/twemoji.browser.js"}`. This would tell Webpack, Browserify, etc to use the smaller version and would not trigger auto-polifyll of global object.

There are even other benefits of changing the `global` behavior:

  1. By using "global.location" in your sourcecode, you are implying that all runtimes have a location in the first place, which is not the case. This is browser specific, so there is not problem using `window` instead.
  2. You are forcing all packagers to include a `global` polyfill for the browser. I would argue this is a bad idea, since you don't need extra code to wrap `window.location`. The global polyfill is not only an overhead, it is an overhead right where it hurts. Browser libraries are deployed to all users on every request.
  3. By relying on `global.location` you are assuming the polyfill used will use `window` and not some global scoped object. In other words, if I polyfill global myself without exposing window for twemoji, then twemoji will break anyway.

For a bit more context why I arrived at the same error condition, [please take a look here, where we discuss "mendel", a new javascript build tool](https://github.com/anuragdamle/mendel/pull/1).

**Comment by WebReflection** [comment]
@irae try to imagine for years this project has ben used by millions without an issue.

Your bundling choices can be your own issues but you made few incorrect assumptions, let me explain.

To start with, there's no global reference in [twemoji](https://github.com/twitter/twemoji/blob/gh-pages/2/twemoji.js) at all

the npm version already uses a [fallback object](https://github.com/twitter/twemoji/blob/gh-pages/2/twemoji.npm.js#L1).

browserify complains if I use `window` and in browserify `global` is the `window`.

On the server side everything works as expected already.

> By using "global.location" in your sourcecode, you are implying that all runtimes have a location in the first place

No. That is used on npm file only and in CommonJS `global` is **always defined**.
If there is no location, like there would be in browserify, it's used, otherwise it doesn't matter.

> You are forcing all packagers to include a global polyfill for the browser. 

Absolutely not. There are all files you want in here:
https://github.com/twitter/twemoji/tree/gh-pages/2

AMD, npm, browser, browser.min and the browser version shouldn't be bundled, it should be through the CDN.

We're not encouraging anyone to bundle twemoji here indeed, the whoe purpose of the CDN is to not have it bundled in order to improve UX.

> By relying on global.location you are assuming the polyfill used will use window and not some global scoped object. 

Not at all. `global` is entirely useless, it's just for the protocol check and nothing else. It has no real benefits/purposes.

An older ticket was discussing about dropping `http:` version all together and use always `https:` so that global wouldn't exist at all in the source code.

That's most likely to happen than fixing bundling issues, and of course once the ES2015 module is available cross browser, we'll push a version that exports the library as default.

Last, but not least:
```js
const global = global || window;
```
This library is compatible with every engine don to older IE, nothing that needs transpilation will ever land in here, unless inside the ES2015 native module (which is not built yet).

### As Summary

If you think the problem is the `package.json` and it takes nothing to make it work under WebPack too, please file a PR since that won't need code changes.

If you think the code is wrong, please read again my previous explanations about why the code is like that and it worked for millions so far.

Best Regards

**Comment by irae** [comment]
That's a very interesting discussion and I thank you for the explanation and the time you've set aside to write it. It gives me better ground for continuing the discussion with less friction.

I think you have a lot of good points about `global` being better than window. But the fact that browserify complains about "window" implies to me that this code is not quite yet to perfection. Yes, you make the CommonJS compatible with node, but development landscape has shifted a bit in recent years and npm and CommonJS are heavily used in the browser, as well as the upcoming standard for javascript modules (import ,exports.default, etc), still in later stages of approval.

Here is what happens right now and I still think it is not optimal:

  1. Your code is written in pure javascript, without any module system, and only needs to access `location`, which BTW is available in the browser global scope, in `window.location` and in `document.location` with some interesting slight differences when frames/iframes are bing used.
  2. You have a build step that wraps it to make it compatible with  CommonJS and other runtimes
  3. Some people use it through npm to use it in isomorphic or browser only aaplications.
  4. Build tools detect global and insert a global polyfill that otherwise would not be present
  5. Code shipped to users have global polyfill and your CommonJS wrapper in the bundle payload, to get `location` which is available in so many scopes.

Although I agree with your points, I still think the end result is not optimal. Be it Browserify or Webpack, or any other bundler being used, we are still shipping unnecessary code.

I don't think this issue is isolated in Twemoji at all. The React/Redux ecosystem, for instance, has lots of junk code in production packages due to their choice of writing in ES-Next. Every single project is solving this in a different way and byte sizes and runtime performance are being affected, most of the time inadvertently by application developers.

I am not sure what the perfect solution will be, I was just arguing that the issue should be kept open until someone has enough time to dig into it. I only maintain Mendel, as explained before, and we are trying to stand your ground that no bundler should have in it's defaults to include runtime polyfills, so we will likely have a plugin to include global if needed, but not as a default operation, like Browserify and Webpack provides. I think this only adds to the problem, instead of solving it. Transparent and with more code injected is making it hard to build large applications with small payload, most of this code not even Rollup is capable of removing, so we are trying to fix it by making everyone using mendel aware of that and fixing the root cause instead. Lets see how it goes for us.

Thank you again for your time! This was very enlightening.
