### ISSUE TITLE
Another License Question

### ISSUE THREAD

**Issue by jmgconesa** [twitter/twemoji#248]
Hi guys!
I want to make a product which includes twitter emojis and as you know they are an open source (https://twitter.github.io/twemoji/). They are already in the market with the exactly same product that what I am going to sell. I was wondering that I can use them in the product´s packaging too if I put the proper attribution (https://creativecommons.org/licenses/by/4.0/legalcode) in the online marketplace where I am going to sell the product.
Do you agree that with a good referencing in the website I should not have any legal issues?
Thank you very much.

**Comment by evilshashanks** [comment]
Yes! There should not be any problems whatsoever if you are putting the license on your product and should just go on with the selling.

**Comment by jmgconesa** [comment]
Great, thank you very much. Could I put the license on the website instead of the packaging if I am going to sell it online?

**Comment by El-Mahbub** [comment]
With two license on this project. Can we use twemoji for our web, if our web like twitter or facebook ?

**Comment by bhaggs** [comment]
When putting the attribution on your website, that is intended to cover the usage of Twemoji in its digital form on the website and would not cover attribution for when being used in physical form as graphics on packaging.

I assume that the packaging of your product will also include other copyright and trademark information, which would be an appropriate place to also include the Twemoji license.

In the case of the packaging only the license information for the graphics would need to be included as you're not using the script (obviously).

> Copyright 2018 Twitter, Inc and other contributors
> Graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/

**Comment by vmasto** [comment]
Hi @bhaggs sorry to bother again on a further question on licensing (thought it'd be best not to open an entirely new issue one it).

In the scenario where we want to use an emoji on a physical (purchased) postcard created via a mobile app (imagine a postcard template within an app where the user can write text which could contain emoji) would the attribution be sufficient in the app under the postcard template itself or would you require it on the printed material as well? Asking mainly because the Postcard is full-paper/print and quite inflexible so trying to understand options.

Thank you very much for your input in advance.
