### ISSUE TITLE
Replace 274e or add new version: red, instead of green

### ISSUE THREAD

**Issue by felixactually** [twitter/twemoji#285]
Below is an edit of 274e. The original is green. This does not make sense for an X. Its counterpart, a checkmark, is green, which is correct. But this one would make more sense as red. Can it be replaced or a new one added with red instead of green?
![274e_red](https://user-images.githubusercontent.com/38003255/39050337-f17abd38-449c-11e8-96c1-29d7b04f95ac.png)

**Comment by raulriera** [comment]
❎✅

These are the Unicode counterparts. I would like for Twitter to not steear away from it

**Comment by felixactually** [comment]
![image](https://user-images.githubusercontent.com/38003255/39062950-397e2448-44c1-11e8-989a-faa9d1a172d0.png)
This is what appears on my screen. Is it different for you or something? A green cross? Or are you advocating for this change and I am just confused? To clarify: The image I uploaded is what I want 274e changed to. A red background instead of a green background.

**Comment by raulriera** [comment]
This is how appears for the Apple Emoji Font.

<img width="781" alt="screen shot 2018-04-20 at 12 45 54 pm" src="https://user-images.githubusercontent.com/24159/39063342-c821b774-4498-11e8-86e1-27e1b1e544af.png">

You can see the full array here, it does look like some are red https://emojipedia.org/negative-squared-cross-mark/

**Comment by felixactually** [comment]
Well, regardless of what Unicode does, is it possible to have a red version added? It makes a lot more sense than green. Green makes sense for a check, but not a cross. Green is positive and red is negative, and using green for both negative and positive is just confusing.

**Comment by Crissov** [comment]
I agree that reddish cross our background makes more sense, although sadly some vendors have changed their design to be better compatible with Apple.

**Comment by felixactually** [comment]
But can a new one be added with a red background? I see you're a contributor. Would you be able to implement this?

**Comment by jdecked** [comment]
We won't be changing these right now.

**Comment by MyriaCore** [comment]
I know this issue is closed, but if the rationale for that is as @raulriera mentioned - that :negative_squared_cross_mark: and :white_check_mark: are unicode counterparts, and therefore should have the same background color - I'd like a link to the unicode spec that mentions this. I couldn't find anything like that in the [UTS for emojis](https://unicode.org/reports/tr51/).

I'm sure it's somewhere, I'm not saying anyone's wrong, but since I'm unfamiliar with unicode spec / emoji spec, I just don't know where to look for it. Could anyone link it here?
