### ISSUE TITLE
Using Prettier for consistent Indentations and formatting of Code 

### ISSUE THREAD

**Issue by prashant-andani** [twitter/twemoji#349]
We shall have a prettier setup to have a consistent and formatted code?
I would be more happy to contribute...

**Comment by WebReflection** [comment]
twemoji is **one file** and it's fairly consistent with itself.

That file, is also basically untouched, single API change a part, since 6th of November 2014, with zero bugs filed for the JS part of this project.

That makes twemoji:

  * battle tested, extremely robust (a rewrite might have undesired side-effects)
  * works out of the box in every single browser (a rewrite might have undesired side-effects)
  * it required so far close to zero maintainance

Accordingly, I wonder which part prettier would solve here, since API changes are likely to happen, bugs to solve are likely to not happen, and the source code is well indented, documented, and I believe also very easy to read.

Accordingly, what issue are you trying to solve, proposing a tool to format a single, already formatted, file?

**Comment by jdecked** [comment]
As @WebReflection points out, adding Prettier to Twemoji would have a relatively low payoff.
