### ISSUE TITLE
SVG files removed from node_modules/twemoji after 12.0.3

### ISSUE THREAD

**Issue by chibicode** [twitter/twemoji#356]
It seems that [this change](https://github.com/twitter/twemoji/commit/171655247d970c82579e42dd450c14e3415631c1) introduced in 12.0.3 removed `2/svg/*.svg` files from what's published on npm. Was this intended? I'm importing those svg files in my code, so I had to revert to 12.0.2 to keep it working.

You can check by inspecting `node_modules/twemoji/2` and:

- On 12.0.2 and earlier, there's the `svg` folder
- On 12.0.3 and later, the `svg` folder is misssing

**Comment by chibicode** [comment]
If this was not intended, I created a PR to fix this: https://github.com/twitter/twemoji/pull/357/files

**Comment by n8downs** [comment]
Hello @chibicode! I did intentionally remove svgs from our published npm package. The fact that they were included looked to me like an oversight in the `.npmignore` blacklist, and having assets included in the JS module takes up a fair amount of space for an otherwise simple JS dependency.

However, I'd be interested to hear more about your use case of importing the svgs so that we can see about finding a way to achieve what you're looking to do without bloating the npm download.

**Comment by chibicode** [comment]
@n8downs thanks, I see. I was using https://github.com/smooth-code/svgr to transform svg files inside `node_modules/twemoji` to react components. I'll just download them from GitHub.

**Comment by n8downs** [comment]
@chibicode Got it, thanks for explaining!

**Comment by Menci** [comment]
You can use https://www.jsdelivr.com/package/npm/@discordapp/twemoji
