### ISSUE TITLE
Thumbs up looks like a turkey

### ISSUE THREAD

**Issue by jglovier** [twitter/twemoji#39]
I cannot unsee that the thumbsup looks like a turkey.

![image](https://cloud.githubusercontent.com/assets/1319791/6065308/26b03fd8-ad19-11e4-9bf3-7bba62b47fd4.png)

If you are accepting pull requests, I will submit one.

**Comment by soffes** [comment]
Amazing.

**Comment by caniszczyk** [comment]
-_-

**Comment by jmdarts007** [comment]
Amazing

**Comment by jglovier** [comment]
So.... :+1: for pull request??

Here's what I came up with as an alternative. Happy to make adjustments based on feedback.

![image](https://cloud.githubusercontent.com/assets/1319791/6153245/4f7968ae-b1f1-11e4-9f1a-baa7489d1bb9.png)

And at smaller scale:

![image](https://cloud.githubusercontent.com/assets/1319791/6153256/66f080d0-b1f1-11e4-8171-b39e455baa54.png)

**Comment by jimmybrancaccio** [comment]
That definitely looks way better :+1:

**Comment by reFX-Mike** [comment]
+1

**Comment by wp9015362** [comment]
> @jglovier wrote:
> 
> Here's what I came up with as an alternative. Happy to make adjustments based on feedback.

I think your alternative looks better, but still not ideal.

Because:

If you look at some of the other Twemojis which involve a fist:

"White up pointing index" Twemoji:

![Image](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/72x72/261d.png)

"Victory hand" Twemoji:

![Image](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/72x72/270c.png)

"Raised fist" Twemoji:

![Image](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/72x72/270a.png)

Then you can see that the lines between their fingers are white. And those white lines are thin.

Others, like the:

"Thumbs up sign" Twemoji:

![Image](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/72x72/1f44d.png)

"Thumbs down sign" Twemoji:

![Image](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/72x72/1f44e.png)

"Fisted hand sign" Twemoji:

![Image](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/72x72/1f44a.png)

have brown lines between their fingers and the lines are thick.

There are some more Twemojis which involve hands/skin where on some on of them thin white lines are being used in the design while on others thick brown lines are being used in the design.

I don't understand why there has to be this inconsistency. It looks, well, inconsistent and bad.

IMHO the Twemojis which are using the thin white lines look much better than the ones which are using the thick brown lines.

So, IMHO, the "thumbs up sign" Twemoji, the "thumbs down sign" Twemoji and the "fisted hand sign" Twemoji should have thin white lines between their fingers, instead of having thick brown lines.

So, any chance you could make it like that, so that the "thumbs up sign" Twemoji, the "thumbs down sign" Twemoji and the "fisted hand sign" Twemoji would be more consistent with the "White up pointing index" Twemoji, "Victory hand" Twemoji, "Raised fist" Twemoji and so on?

Regards

**Comment by jglovier** [comment]
@wp9015362 thanks for the awesome feedback!! You are so right re: inconsistent styles. I do like the idea of sticking with the white outline, although I'd love to hear from @caniszczyk or another maintainer before I go running too hard in any direction.

I know they commissioned the artwork for these from Icon Factory, and they were probably art directed externally from the open source efforts. From what I've seen the pull requests here have mostly been code related - not artwork - so I'd love if someone could confirm is this change is something the maintainers are even interested in?

**Comment by wp9015362** [comment]
@jglovier :

You're welcome :smiley: .

There's one thing I would like to ask while you are here if you don't mind:

I saw that on you're website:

http://joelglovier.com/

you're saying:

>  I work at GitHub where I’m part of the Creative Team.

GitHub currently seems to be using the Apple Emoji set in it's markdown, see:

https://github.com/blog/1289-emoji-autocomplete
https://github.com/blog/816-emoji

I am wondering:

Where does GitHub take it from?

And why does GitHub use the Apple Emoji set and not the Twitter "Twemoji" Emoji set?

And are there any plans to replace it with the Twitter "Twemoji" Emoji set?

Regards

**Comment by jglovier** [comment]
@wp9015362:

>Where does GitHub take it from?

We use: https://github.com/github/gemoji

>And why does GitHub use the Apple Emoji set and not the Twitter "Twemoji" Emoji set?

Primarily because the Twitter set was not a thing when we implemented Gemoji.

**Comment by wp9015362** [comment]
> @jglovier wrote:
> 
> We use: https://github.com/github/gemoji

So, does that mean that the Apple Emojis are open source as well?

Sorry if that might be a little off-topic, but since you are already here...

Regards

**Comment by jglovier** [comment]
@wp9015362 I don't maintain the Gemoji project, so you'd have to refer questions about that project to that repository.

**Comment by wp9015362** [comment]
> @jglovier wrote:
> 
> although I'd love to hear from @caniszczyk or another maintainer before I go running too hard in any direction.

@caniszczyk :

Any update?

Regards

**Comment by shurcooL** [comment]
I've seen this issue reported independently (https://src.sourcegraph.com/sourcegraph/.tracker/248), so I just wanted to say :+1:. I think improving the thumbsup, thumbsdown icons will help make twemoji even better. Thanks!

**Comment by WebReflection** [comment]
[V2 has landed](https://github.com/twitter/twemoji#unicode-80-and-diversity) with 1661 covered emoji VS just 874 in previous version.

Easy way to update?
prefix `/twemoji.min.js` from MaxCDN via `2/twemoji.min.js` and you're good to go.

P.S. it's probably still like a turkey, no designer ever read this repo

**Comment by reFX-Mike** [comment]
> P.S. it's probably still like a turkey, no designer ever read this repo

Yeah, except @jglovier who even asked if it's OK to add the pull request for his much better version.

@WebReflection Please hand the maintenance over to someone else. Your heavy-handed, ignorant and almost insulting stewardship hurts this project more than anything.

We switched to Emoji One a while ago.

**Comment by WebReflection** [comment]
@reFX-Mike thanks for your kind words and you are welcome for the latest release.

As reminder, I take care only of the JS side of this project and I'd love to have some graphic designer responsible for this repository.

If I leave here, you'll have zero maintenance, design and assets speaking.

As second reminder, I'm volunteering here, I don't work at twitter since 2014, and I'm not willing to take insults for free.

Thanks for your understanding.

**Comment by reFX-Mike** [comment]
@WebReflection then stop volunteering here. You completely ignore people (like you ignored @jglovier ), then claim that nobody submitted anything (which is obviously wrong) and now pout when called out. 

I've experienced your "help" first-hand, when I offered to fix the gray moons (something I could have done in note-pad, since SVG are very simple text-files) but you had to "make sure" we're all legit etc.

You. Are. Hurting. This. Project. More. Than. If. You. Stopped. Contributing. At. All.

**Comment by WebReflection** [comment]
you keep not understanding how this repository works. It's not in my will, nor power, to take assets/design/graphic decisions whatsoever.

I've explained it to you a while ago, and I'll keep pointing at this very same post from now on every time you'll keep ignoring this fact.

I'm not maintaining the assets part of this project, you are complaining with the wrong person and I won't tolerate any other personal insult to me in this project.

Take care.

**Comment by jglovier** [comment]
This thread is getting out of hand. I appreciate the passion for results, but @reFX-Mike being rude doesn't help open source. I'm certainly bummed to see the latest version not include a fix for this issue, and the lack of even a direct response. But I also appreciate the difficulty of maintaining a large open source project, and the work that @WebReflection is putting in. She should not be reprimanded for a problem which was not hers to address.

To the maintainers of this project, I'd suggest locking the discussion on this thread to prevent further mis-expressed frustration or superflous +1 comments. 

And thanks for all of your efforts on this project. :heart:

**Comment by jglovier** [comment]
Also, if the decision to not accept design changes via this repository is an intentional one, then it might be worth adding a `wontfix` label to this issue just for reference and clarification for future visitors.

**Comment by reFX-Mike** [comment]
@jglovier Just FYI: Andrea is not a "she" ;)

**Comment by WebReflection** [comment]
> She should not be reprimanded for a problem which was not hers to address.

it's a `he` but Andrea is male name only in Italy, where I come from ... I'm kinda used to it, that's why people keep telling me I should put my face on my avatar.

I have to admit I like when people act differently mistaking my name, no matter if they support me or not :-)

Thanks for your understanding. If you check the commit history of this project, all new assets landed in one shot and I have no contact at all with any designer at twitter.

All I can do is push for it like I've done already in order to obtain this current release.

Examples:
https://github.com/twitter/twemoji/issues/116
https://github.com/twitter/twemoji/issues/103#issuecomment-173745303

Plus private messages with some contact I still have in there, unfortunately not a single designer.

Sad to find @reFX-Mike like "reward" for my effort ... but sure, I am hurting so much in here.

Cheers

**Comment by jglovier** [comment]
>it's a he but Andrea is male name only in Italy, where I come from ... I'm kinda used to it, that's why people keep telling me I should put my face on my avatar.

@WebReflection whoops - very sorry about that.

**Comment by WebReflection** [comment]
no reason to be sorry, it's a common mistake.

Once a manager in a famous company shaked my hand telling me: "_welcome to this compani, Ayako_" and after that shake **her** hand saying "_and welcome to this company to you as well, Andrea_"

Names are fun :-)

About flagging as `won't fix`, I'll do that because I've closed it assuming since all new assets landed and no change was made, there was no bug to consider so, actually, it is a won't fix.

Again it's very difficult to have a statement from anyone about this repo assets.

Contributors list is made of developers with no, or kinda little, graphical skills.

Apologies but that's really not my fault, I was going to fork this and drop entirely the assets part ... I'm very happy we released version 2 today (actually everything arrived the 29th of February, can you believe it?)
