### ISSUE TITLE
SVG - Size ignored

### ISSUE THREAD

**Issue by SoftCreatR** [twitter/twemoji#397]
Dunno, if this is the expected behavior, but if it is, consider this as a feature request.

When using the SVG version like this:

```
twemoji.parse(document.body, {size: 16, folder: 'svg', ext: '.svg'});
```

The size parameter is being ignored. Instead, it should append the size as parameter in the img-Tag, that it generates.

As a workaround, you can simply create a custom CSS rule:

```
img.emoji {
    width: 16px;
}
```

But i would like to have this automated (or even optionally automated).

**Comment by range-of-motion** [comment]
What this guy said ☝️

**Comment by WebReflection** [comment]
This is probably a documentation gotcha: [the `size` parameter](https://github.com/twitter/twemoji#size) result into the asset that's being loaded, it has nothing to do with the image size, as that would be eventually `width` indeed.

You can use size 16 emoji and have width 128px, or you can use size 72 emoji, and show these into 16px images.

As CSS *is* the way to set image width without breaking ratio, that's the suggested way, but changing size behavior **would break** every library user that understood what was the size about, or never touched it, as by default, that would result into every default suddenly showing 72px images, instead of the size they decided via CSS.

However, if you really want JS to enforce the emoji size, you can simply write this instead:

```js
function adjustSize(target, width) {
  [].forEach.call(target.querySelectorAll('img.emoji'), function (img) {
    img.width = width;
  });
}
```

I won't close this issue 'cause I've been long time away from this project (gosh, so many users and never a real JS bug to date!!!) ... but I strongly suggest to ignore this request, as it's breaking, not meant to work the way you think, hence there's nothing to do in here.

Best Regards
