### ISSUE TITLE
Why are the filenames for emojis on maxCDN so inconsistent? How are supposed to find the filename for an emoji?

### ISSUE THREAD

**Issue by GNUGradyn** [twitter/twemoji#419]
The general format to get a 72x72 PNG of an emoji is `https://twemoji.maxcdn.com/v/13.0.0/72x72/[codepoint]-[codepoint].png` (using - to seporate emojis made of multiple unicode characters)

But not all emojis follow this rule

☺️ should be 263a-fe0f.png, but is just 263a.png. In fact, U+FE0F seems to be emitted from every emoji that uses it

🙍‍♂️ should be 1f64d-200d-2642.png but I wasn't even able to figure out the correct file name. The closest thing I was able to find was 1f64d.png, the genderless version. 

How is one supposed to figure out the file name for an emoji?

Update: found the filename for 🙍‍♂️, it is 1f64d-200d-2642-fe0f.png. It has the U+FE0F not emitted. How come some emojis emit it but not all of them???

**Comment by WebReflection** [comment]
In the source code you can find how the image name is retrieved, which boils down to:

```js
var UFE0Fg = /\uFE0F/g;
var U200D = String.fromCharCode(0x200D);
var toCodePoint = twemoji.convert.toCodePoint;
function grabTheRightIcon(rawText) {
  return toCodePoint(rawText.indexOf(U200D) < 0 ?
    rawText.replace(UFE0Fg, '') :
    rawText
  );
}
```

There is eventually a `twemoji.convert.fromCodePoint` to rollback.

The `\uFE0F` is removed because emoji are inconsistently implemented across browsers, were few might, and few others might not, consider/use that char, so the function tries to normalize for all browsers.

**Comment by WebReflection** [comment]
forgot to answer the second question:

> How come some emojis emit it but not all of them???

it's written in here https://github.com/twitter/twemoji/blob/master/scripts/build.js#L337-L350

**Comment by GNUGradyn** [comment]
Thank you for the quick response. Including U+FE0F when U+200D is present and emitting it when it's not seems to work for every emoji except 👁️‍🗨️, which should have a file name of 1f441-fe0f-200d-1f5e8-fe0f.png. I wasn't even able to find the correct URL because even the official twemoji.js just incorrectly adds a 👁️ emoji and a 🗨️
![image](https://user-images.githubusercontent.com/20762604/83573826-6c53fc00-a4e9-11ea-9264-33a50aae196d.png)

**Comment by WebReflection** [comment]
the `twemoji.js` has no knowledge about file names, and it uses a pre-generated regular expression to parse emoji. If an emoji is unknown, or not implemented, it will parse what it knows, and what is implemented.

Accordingly, it is very possible that the :eye_speech_bubble: is not implemented yet, and what you see is just the combination of the two emoji.

That's also how unicode spec'd on purpose emoji, the fallback should tell the user intent, in this case precisely the eye and the speech bubble.

**Comment by jdecked** [comment]
👁️‍🗨️ is indeed implemented — the file you're looking for is at https://twemoji.maxcdn.com/v/13.0.0/72x72/1f441-200d-1f5e8.png. This is because of #405 — to match the Unicode spec exactly, we need to sit and do an audit of all of our emoji sequences to ensure that we're handling the fully qualified sequences for each emoji as first-class citizens, followed by any unqualified sequences we've previously handled or which [the emoji-test.txt file from Unicode](https://unicode.org/Public/emoji/13.0/emoji-test.txt) specifies (e.g. 1f441-200d-1f5e8 for 👁️‍🗨️).

Unfortunately, this project is staffed by people who don't work on it as their only day job (in fact, it's very much a spare time volunteerism sort of thing), which is why bug fixes are not so quick sometimes. I'm closing this as a duplicate for now because fixing #405 will also fix this, but if you'd like a quicker fix than we can provide, PRs are always welcome.

**Comment by BrianHung** [comment]
> This is because of #405 — to match the Unicode spec exactly, we need to sit and do an audit of all of our emoji sequences to ensure that we're handling the fully qualified sequences for each emoji as first-class citizens, followed by any unqualified sequences we've previously handled or which the emoji-test.txt file from Unicode specifies (e.g. 1f441-200d-1f5e8 for 👁️‍🗨️).

One way to migrate to fully qualified sequences while also supporting unqualified sequences in the twemoji parser might be to use the [emoji.json](https://github.com/iamcal/emoji-data/blob/master/emoji_pretty.json) from emoji-datasource. To resolve the twemojiURL, just convert all unqualified sequences to qualified sequences.

https://github.com/twitter/twemoji-parser/blob/master/src/index.js#L22-L28
