### ISSUE TITLE
👁️‍🗨️ is difficult to view in gray dark-themes

### ISSUE THREAD

**Issue by MyriaCore** [twitter/twemoji#420]
👁️‍🗨️, or "eye in speech bubble", is a primarily dark gray emoji that has no shading or gradient on it to distinguish it from potentially dark backgrounds. This is problematic in applications like discord that employ a dark-theme with a dark gray background, which renders the emoji practically invisible at reasonable viewing distances:

![image](https://user-images.githubusercontent.com/35076430/84319960-e8c88980-ab3e-11ea-902e-5bc4ceaecd46.png)

Note that this problem is most severe for dark gray backgrounds, which don't have much other colors in them. If the background is tinted with blues or purples, like the background for twitter's darktheme, 👁️‍🗨️  becomes way easier to see. However, many dark-themes tend to be gray, such as the dark-themes used in discord, vscode, riot.im, spotify, duck duck go, and other popular sites and services. 

I'm not super familiar with the style requirements for this specific emote, but this could be remedied in a number of ways:
- [Microsoft's variant](https://emojipedia.org/microsoft/windows-10-may-2019-update/eye-in-speech-bubble/) of this emote makes the emote primarily white, and breaks with the style of other variants of 👁️‍🗨️  by not cartoonifying the iris. Combined with the black border, this makes the emote clearly distinguishes on both light *and* dark backgrounds.
  
   ![image](https://user-images.githubusercontent.com/35076430/84320324-773d0b00-ab3f-11ea-92f8-39c3815feec4.png)
- The [Android 7.0 variant](https://emojipedia.org/google/android-7.0/eye-in-speech-bubble/) was primarily light-gray, which is slightly worse on light backgrounds than on dark backgrounds, but is still viewable on both:

   ![image](https://user-images.githubusercontent.com/35076430/84320516-cb47ef80-ab3f-11ea-83e5-33d1212e48ee.png)
- The [JoyPixels Variant](https://emojipedia.org/joypixels/5.5/eye-in-speech-bubble/) of this emoji still uses primarily dark colors, but has a slight gradient so it's easier to pick out on a dark background:

   ![image](https://user-images.githubusercontent.com/35076430/84320676-0cd89a80-ab40-11ea-858e-7a84e249a1bf.png)

Personally, I think the Android 7.0 approach is the way to go, because it's more consistent with twemoji's pre-existing style than the other examples.

**Comment by MyriaCore** [comment]
There also happen to be many other emojis that are similarly problematic, including, but not limited to:

- animals: `spider` (:spider:), `ant` (:ant:), `water_buffalo` (:water_buffalo:), 
- symbols: `heavy_plus_sign` (:heavy_plus_sign:), `heavy_minus_sign` (:heavy_minus_sign:), `heavy_division_sign` (:heavy_division_sign:), `heavy_multiplication_x` (:heavy_multiplication_x:), `heavy_dollar_sign` (:heavy_dollar_sign:), `currency_exchange` (:currency_exchange:), `tm` (:tm:), `copyright` (:copyright:), `registered` (:registered:), `wavy_dash` (:wavy_dash:), `curly_loop` (:curly_loop:), `end` (:end:), `back` (:back:), `on` (:on:), `top` (:top:), `soon` (:soon:), `heavy_check_mark` (:heavy_check_mark:),
- misc: `spades` (:spades:), `clubs` (:clubs:), `telephone_receiver` (:telephone_receiver:), `dark_sunglasses` (:dark_sunglasses:), 

I might open a new issue to track these emojis too, or revise the current issue to reflect all these new emotes, but the common theme here is that these emotes have primarily dark colors, and no features to distinguish them from a potentially dark background.

**Comment by MyriaCore** [comment]
I'll edit this to provide a better list of suggestions here, but a ton of these emojis can be changed by changing the color:

### Appropriate color changes
- animals:
  - `spider` (:spider:): green, brown, light grey
  - `ant` (:ant:): green, red, brown, light grey
  - `water_buffalo` (:water_buffalo:): brown, light grey

**Comment by AbyssStudios** [comment]
This sounds cool, I will make a pr. What is this policy for making a pull request?

**Comment by MyriaCore** [comment]
not sure TBH, although I'm sure if you just make a feature branch and a commit for each image edited, it'll be no problem.

**Comment by jdecked** [comment]
Hey folks, while I appreciate the discussion here, this isn't something we're planning to change at the moment. We chose a colour that tries to be visible across as many dark backgrounds as possible, with the understanding that it wouldn't be able to be visible across all. As for the gradients solution: we don't use gradients in Twemoji at the moment and don't plan to change it in the near-term.

There's not necessarily a "policy" for making a pull request per se, but I'm an engineer, so if it's a pull request for an artwork/design change, I have to go ask the designer I work with on Twemoji for his feedback first. Same goes with issues asking for artwork changes (which, at the moment, are most of them). I go through these whenever I have spare time which is why sometimes it takes me a bit long to reply to a PR/issue — but I do set aside some time a minimum of once a month to review anything I've missed.

If it's a code-related PR/issue, it's a lot easier to review since I'm the only engineer working on this at the moment — but Twemoji is built to be compatible with [Twemoji Parser](https://github.com/twitter/twemoji-parser), so any changes here have to still work there too (or have a corresponding PR to twemoji-parser that makes it work). The regexes in Twemoji Parser are understandably difficult to edit; they're generated by a closed-source Scala project that's at the top of my list for open sourcing in the future to make contributing code substantially easier. Docs-only PRs, on the other hand, are particularly easy to accept.

We're always happy to receive suggestions — artwork, code, or otherwise — but we do prioritize remaining consistent with other major vendors (e.g. Apple, Facebook) while giving the emojis a "Twittery" feel, so it's important to chat about your suggestion in an issue first before making a PR so that you don't spend a lot of time working on something that we might have good reasons for rejecting. Even though we might not accept all of the suggestions, we do review them all and think about them. I try to briefly explain why when we don't accept a suggestion, which I hope is helpful.

That all said, hope that gives some context into how to contribute most effectively — closing this for now since we won't change the dark emojis, but if you have any ideas on how to make contributing easier/better, feel free to open an issue with your thoughts and we can chat there.

**Comment by DerSaidin** [comment]
@MyriaCore nicely presented and linked issue report :)

+1 to this request. Emoji like `:heavy_plus_sign:` really do [not work well with Discord dark theme.](https://support.discord.com/hc/en-us/community/posts/360054922591/comments/4406335415319)

> We chose a colour that tries to be visible across as many dark backgrounds as possible, with the understanding that it wouldn't be able to be visible across all. As for the gradients solution: we don't use gradients in Twemoji at the moment and don't plan to change it in the near-term.

> ...we do prioritize remaining consistent with other major vendors

What about adding an outline? This would be consistent with what [Microsoft does](https://emojipedia.org/plus/) (several other emoji libraries on that list do too).

Imo an outline also looks the same on twitter default, and looks at least as good on twitter dark:

![heavy_plus_outline_twitter](https://user-images.githubusercontent.com/1215709/134105284-e8843ed3-eeec-4a50-a015-415b22329818.png)

And much better on Discord dark:
![discord_examples](https://user-images.githubusercontent.com/1215709/134115227-97ea7c7e-94c4-46b0-9245-6251dc7bfac9.png)

In these examples I used colour #6e767d for the outlines.
