### ISSUE TITLE
Belarusian flag

### ISSUE THREAD

**Issue by linxlan** [twitter/twemoji#444]
I would like to ask you to add an official emoji with the White-red-white flag (see the attached photo) as a sign of support and solidarity with the peaceful protesters of Belarus, it will be a nice support from your side
https://en.wikipedia.org/wiki/Flag_of_Belarus#White-red-white_flag
![n40l4t6oceh51](https://user-images.githubusercontent.com/29060641/97672841-d0302000-1a9b-11eb-8fd6-092e2e5f68fd.png)

**Comment by jdecked** [comment]
While we're 100% in support of peaceful protests, human rights, and holding governments accountable, we only support emoji which are in Unicode. Because this isn't the official flag of Belarus, we can't change the Belarusian flag emoji to it, and because no additional emoji specifying this flag are part of Unicode, we can't create a special non-standard emoji for it. Sorry.
