### ISSUE TITLE
Expose shouldntBeParsed as a property

### ISSUE THREAD

**Issue by coryosborn** [twitter/twemoji#45]
Unfortunately, when using DOM parsing right now, this attempts to replace emoji characters with image tags inside of a textarea tag.  It would be nice if I could just adjust the shouldntBeParsed regex to exclude textareas.

**Comment by WebReflection** [comment]
nice hint, will do ASAP

**Comment by WebReflection** [comment]
Fied in `v1.2.1` and it should propagate through the CDN soon.

Exposing that RegExp is probably not a good idea since it's also about security and the ability to break a page if the RegExp is somehow modified.

I think it's reasonable to include TEXTAREA and other elements that could contain nodes but should never be parsed so I hope the current change is enough.

Best Regards

**Comment by coryosborn** [comment]
Awesome!
