### ISSUE TITLE
Yarn build not working

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [twitter/twemoji#455]
**Issue:** `yarn install`  worked successfully but on running `yarn build` I'm getting this. Can anyone help me out here?

![image](https://user-images.githubusercontent.com/43600306/102685716-9c09ed80-4208-11eb-94c6-e22dee1766f8.png)

**OS:** Windows 10
**Browser:** Edge

**Comment by jdecked** [comment]
Hey @ShreyaPrasad1209, I suspect this is because in our `package.json`, our build command is `./scripts/build.js` and not `node ./scripts/build.js` (shebangs are unfortunately ignored on Windows). If you change [line 36 in package.json](https://github.com/twitter/twemoji/blob/master/package.json#L36) to `"build": "node ./scripts/build.js"`, does it work?

**Comment by ShreyaPrasad1209** [comment]
Hey @jdecked, I made the changes and got this. I Googled also and applied the fixes given in search results but it didn't work. 
![image](https://user-images.githubusercontent.com/43600306/104119234-133c2880-5354-11eb-87f0-ed9edad572b5.png)

**Comment by jdecked** [comment]
@ShreyaPrasad1209 it seems you're missing a space between "node" and "./scripts/build.js".
