### ISSUE TITLE
How to change :) to :smile:?

### ISSUE THREAD

**Issue by fardeemmunir** [twitter/twemoji#46]

**Comment by WebReflection** [comment]
sorry ... what?

**Comment by fardeemmunir** [comment]
I want users to be able to type in :) and automatically render it as
:smile:. Like the common chat applications.

On Mon, Feb 16, 2015 at 6:20 PM, Andrea Giammarchi <notifications@github.com
> wrote:

> Closed #46 <https://github.com/twitter/twemoji/issues/46>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/twemoji/issues/46#event-236281634>.
>



-- 
Fardeem Munir
www.erubai.com
@awesomerubai

**Comment by WebReflection** [comment]
Those are "emoticons", quite a different thing.

Here is about emoji, something new for most old chat apps out there.
Check your phone, as example, you most likely have a button to insert emoji instead of :)

In few words you probably need a panel with a list of emoji so that once you click one that gets inserted in the textarea or you need your own parser that changes :) and who knows what else into emoji.

This project is about emoji, not conversion from Unicode standard emoji to some "random" bb-code style emoticon implementation so this is not a bug, an issue, or anything emoji related.

Thanks for your understanding.

**Comment by fardeemmunir** [comment]
Oh ok. Thanks for the detailed answer. I leaned something today :smile:
