### ISSUE TITLE
Support for custom / user-defined emojis

### ISSUE THREAD

**Issue by Seldaek** [twitter/twemoji#462]
**Is your feature request related to a problem? Please describe.**
We are looking at adding user-defined emojis to our web app, and would like to use twemoji to convert those to images too if possible.

**Describe the solution you'd like**
We plan on storing user-defined emojis within the Unicode [private use areas](https://en.wikipedia.org/wiki/Private_Use_Areas) to avoid clashes with anything else. So we'd like to be able to do something like:

```
twemoji.parse(input, {
    customEmojis: {
        "\uF8FF": "https://url-to-image"
    }
})
```

**Comment by WebReflection** [comment]
My 2c,
  beside the fact your example is invalid JS (named properties in array), I think the issue is more complex than that, as this library heavily relies on the contract between [this regexp](https://github.com/twitter/twemoji/blob/master/scripts/build.js#L12) and the list of provided assets.

In few words, your "*simple change*" would likely require a whole rewrite of this library internal logic, so that it can accept random regular expressions and related callbacks that returns the desired URL.

**Comment by Seldaek** [comment]
Hah sorry I meant to do an array of objects and then got sidetracked while lookup the unicode codepoint again. Fixed code sample.

I was hoping these custom replacements might be done in a second pass but given the [loop here](https://github.com/twitter/twemoji/blob/1f79250bdc1fd54bf9f963b9dc7807de9587da83/scripts/build.js#L388) it seems rather difficult to do a second loop below for custom emojis, so indeed appending custom codepoints to the default regex would be the ideal solution, but I can see definitely see you may not want to cater to this use case.

**Comment by WebReflection** [comment]
I think I wrote this in 2014 or sometime around it ... there's code that takes care of IE6 quirks too ... but here my take: today I'd create a generic library that can crawl the DOM and place safely replacements. Finding and replacements would be retrieved through a set of registered "*handlers*", where each handler has a `{regExp: /.../, source() {}}`, so that *twemoji* would be just the combination of the RegExp + the function to return the right asset, and so could do any other custom library (so it would work for everything, not just emoji).

However, I've also left twitter in 2014 and I don't have personally the need for such library, and neither does my employer so ... I hope I gave at least some reasonable hint on how this could be done in a more flexible, universal, way, to whoever would like to create such library 👋

**Comment by jdecked** [comment]
A lot has changed since 2014, but one thing that remains the same is that if it's not in the Unicode standard, it might as well not exist because we won't be supporting it. We just don't have a need for custom emoji right now. @WebReflection does give a good idea on how this _could_ be done, though, built on top of Twemoji and whatever else someone pleases, which would be really cool to see — especially as a configurable library based on Unicode PUAs.

To give a bit more background, there's actually a closed-source library which we also maintain that's used for generating the regex you propose editing. (I'm working on open sourcing it, but it will take a months-long while.) It would be difficult but not implausible to modify that library such that you could define your own custom emoji which correspond to different Unicode PUA code points. Maybe that's something you want to look out for in the future, but if you're looking for a more short-term solution, look elsewhere. :-)

**Comment by scratchyone** [comment]
For anyone who still wants it, it seems like the library @jdecked was talking about has been open sourced: https://github.com/twitter/twemoji-parser/tree/master/src/scala
