### ISSUE TITLE
Trying to understand what process to follow so submit a Twemoji for a popular hashtag

### ISSUE THREAD

**Issue by RED29** [twitter/twemoji#473]
**Is your feature request related to a problem? Please describe.**
It's very frustrating to see that some popular Twitter hashtags mentions have a Twemoji and some not. The honest question is if there is a submission process ? If yes, where is it ? Is this process transparant and open for anyone ? What criteria are there ?

**Describe the solution you'd like**
A transparant and open process to able to submit a special Twemoji, just like #Bitcoin and just recently #Binance have (this one was to be honest a surprise why it had a Twemoji). 

If this process just simple as creating an issue here, than I would like to submit a the Ethereum Twemoji. If this is ok, than love to supply all svg/media for this Twemoji.

**Describe alternatives you've considered**
An explanation how this Twemoji hashtags works.

**Comment by jdecked** [comment]
The little emoji after hashtags on Twitter are **not Twemoji**. They are hashflags. The art styles are similar because they're both made by Twitter. They're added for special occasions by Twitter (e.g. Autism Acceptance Month, Mars 2020) or paid for by companies wanting to run a marketing campaign. I have no idea how you get them as a company or other non-Twitter entity. Closing since this isn't Twemoji-related.

**Comment by RED29** [comment]
Thanks for explaining.
