### ISSUE TITLE
non-standard codepoint for “Santa Claus (Father Christmas)” and “Mrs. Claus”

### ISSUE THREAD

**Issue by xDEADC0DE** [twitter/twemoji#492]
I noticed that the codepoints for the emoji “Santa Claus (Father Christmas)” and “Mrs. Claus” used in Twemoji differ from the standard published at https://unicode.org/Public/emoji/13.1/emoji-test.txt :

In Twemoji, the filenames are:
* Santa: 1f468-200d-1f384 (“man, zwj, christmas tree”)
* Mrs Claus : 1f469-200d-1f384 (“woman, zwj, christmas tree”)

But on the Unicode document they are listed as:
* 1F385             ; fully-qualified     # 🎅 E0.6 Santa Claus
* 1F936             ; fully-qualified     # 🤶 E3.0 Mrs. Claus
* 1F9D1 200D 1F384  ; fully-qualified     # 🧑‍🎄 E13.0 mx claus

Is there a reason for this difference?

(both 1F385 and 1F936 are recognized by twemoji.min.js)

**Comment by jdecked** [comment]
@xDEADC0DE both (1f468-200d-1f384|1f469-200d-1f384).(svg|png) and (1f385|1f936).(svg|png) are available as filenames in Twemoji (example: [1f385.png](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f385.png)). While the latter isn't fully-qualified, its existence helps us avoid special-casing certain emoji as the standard evolves towards the gender-inclusive pattern of (person|man|woman)-zwj-object.

I'm going to close this out for now since given the info in this thread, we don't plan to change this right now — but if this is somehow causing problems in a project you're trying to integrate Twemoji into, feel free to reopen with a comment with more info.

**Comment by xDEADC0DE** [comment]
Thank you for your answer, it doesn’t cause any issues I was just a bit surprised :)
