### ISSUE TITLE
Adding Twemoji to sites like Tumblr

### ISSUE THREAD

**Issue by nmh1995** [twitter/twemoji#55]
Is there any way of me adding Twemoji to sites like my Tumblr blog?

I'm wondering this, because if I use emojis on my blogposts, they appear as white boxes, rather than emojis. I was unsure on whether there was a way of implementing Twemoji onto sites like Tumblr, so that this doesn't happen. 

If so, what do I need to put into my code and where? 

Thanks.

**Comment by WebReflection** [comment]
can you modify the HTML template of your blog? If so, you can add the following on the header
`<script defer src="//twemoji.maxcdn.com/twemoji.min.js"></script>`
then you can add the following CSS style
```html
<style>
img.emoji {
   height: 1em;
   width: 1em;
   margin: 0 .05em 0 .1em;
   vertical-align: -0.1em;
}
</style>
```
then you can add a script like the following one
```html
<script>
document.addEventListener(
  'DOMContentLoaded',
  function DCL(e) {
    document.removeEventListener(e.type, DCL, false);
    twemoji.parse(document.body);
  },
  false
);
</script>
```

You can eventually be more specific during the parsing so that you'll grab only posts and/or comments instead of the entire body, resulting in probably better performance.

```html
<script>
document.addEventListener(
  'DOMContentLoaded',
  function DCL(e) {
    document.removeEventListener(e.type, DCL, false);
    for (var el = document.querySelectorAll('div.post-content'), i = el.length; i--; twemoji.parse(el[i]));
  },
  false
);
</script>
```
