### ISSUE TITLE
263A emoji style variant does not look like a normal "smiling face"

### ISSUE THREAD

**Issue by iseulde** [twitter/twemoji#58]
Compare:
http://www.unicode.org/cgi-bin/varglyph?24-263A-FE0F
https://github.com/twitter/twemoji/blob/v1.3.2/svg/263a.svg

**Comment by ericandrewlewis** [comment]
I'd like to request that we remove the blush while we're here. Blush is common in emoji variants of "WHITE SMILING FACE," but its presence implies a secondary emotional dimension which skews the meaning of the most basic emoji. ☺

**Comment by melchoyce** [comment]
+1

**Comment by wp9015362** [comment]
> @ericandrewlewis wrote:
> 
> I'd like to request that we remove the blush while we're here.
> Blush is common in emoji variants of "WHITE SMILING FACE,"
> but its presence implies a secondary emotional dimension
> which skews the meaning of the most basic emoji. ☺

I assume that the "white smiling face" Twemoji probably has a blush to it because the "white smiling face" in the Apple Emoji set, which is arguably the most popular Emoji set out there, has a blush to it.

The developers/designers of the "Emoji One" Emoji set have done it like this as well, see:

https://github.com/Ranks/emojione/issues/50

I agree that it kinda sucks that the Twitter "Twemoji" Emoji set and many other Emoji sets do not have a simple smiling face without a blush because of this.

On the other hand though, if the Twitter "Twemoji" Emoji set would now remove the blush from it's "white smiling face", then the Emojis could easily get lost in translation, as is described in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

Because, an Apple user for example would still see a "white smiling face" with a blush.

That would be bad.

I agree that, in an ideal world, the "white smiling face" Twemoji should not have a blush to it.

But unfortunately we don't live in an ideal world because the "white smiling face" in the Apple Emoji set and other Emoji sets has a blush to it.

And the Apple Emoji set is so popular that removing the blush from the "white smiling face" actually would be bad IMHO.

If Apple would also remove the blush from it's "white smiling face" Emoji, then it would be good of course.

And unfortunately there are even some more Emoji sets which have a blush to their "white smiling face", as can be seen on the big comparison chart over there:

http://emoji.codes/family

Regards

**Comment by wp9015362** [comment]
PS:

This might be of interest for this issue:

It looks like there should be a "slightly smiling face" in Unicode 7.0.

But apparently it's missing in Twemoji.

I submitted an issue for this, see:

https://github.com/twitter/twemoji/issues/65

Regards

**Comment by bhaggs** [comment]
I believe "slightly smiling face" has this covered now as an alternative.
