### ISSUE TITLE
Face size is inconsistent across Twemoji faces

### ISSUE THREAD

**Issue by wp9015362** [twitter/twemoji#60]
Hello,

I just came across a screenshot on the XDA Developers forum, which shows what the Twitter "Twemoji" Emoji set looks like on an Android keyboard, see:

![Image](http://i.imgur.com/Bxf3oQY.png)

Source:

http://forum.xda-developers.com/showthread.php?p=58610497#post58610497

It looks quite good.

But:

As you can see, the face size is inconsistent across the Twemoji faces, which looks quite buggy.

Some Twemoji faces are bigger, some are smaller.

In comparison, here is a screenshot which shows how the ["Emoji One" Emoji set](https://github.com/Ranks/emojione) looks on an Android keyboard:

![Image](http://i.imgur.com/a2bj6Eo.png)

Source:

http://forum.xda-developers.com/showthread.php?p=58610497#post58610497

As you can see, the face size is consistent across the Emoji One faces, which looks much better.

So, could you please change the Twemoji faces so that they all have the same size?

Regards

**Comment by WebReflection** [comment]
oh wow ... you folks are trusting a library [that does this](https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js#L389-L404)?

It's sort of disaster prone library https://gist.github.com/WebReflection/df05641bd04954f6d366 but that's not what you are asking ... so, how about you tell me if those are pngs or svgs or ... ?

Thanks

**Comment by WebReflection** [comment]
btw, in case you are interested in the problems that XSS approach could cause ... https://github.com/Ranks/emojione/issues/61

**Comment by wp9015362** [comment]
> @WebReflection wrote:
> 
> oh wow ... you folks are trusting a library [that does this](https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js#L389-L404)?

Well, I don't really know what you mean, but it seems like they had some kinder words for you than you have for them, see...:

http://emojione.com/blog/congrats-twitter-from-emoji-one/

:wink:

> @WebReflection wrote:
> 
> so, how about you tell me if those are pngs or svgs or ... ?

Actually I am not entirely sure. As I said, I simply came across those screenshots on the XDA Developers Forum and noticed the size inconsistency across the faces.

But what I can tell you is this:

The screenshots come from this post:

http://forum.xda-developers.com/showpost.php?p=58610497&postcount=94

And in his previous post he was talking something about PNGs, see:

http://forum.xda-developers.com/showpost.php?p=58584502&postcount=92

So I assume it's an Android Emoji font he made from PNGs.

And what I also can tell you is:

The size inconsistency is definitely just as noticeable on the PNGs and SVGs which are hosted in your repository.

For example:

The "grinning face with smiling eyes" SVG Twemoji, see:

https://github.com/twitter/twemoji/blob/gh-pages/svg/1f601.svg

is definitely smaller than the "hushed face" SVG Twemoji, see:

https://github.com/twitter/twemoji/blob/gh-pages/svg/1f62f.svg

And the "grinning face with smiling eyes" PNG Twemoji, see:

https://github.com/twitter/twemoji/blob/gh-pages/72x72/1f601.png

is definitely smaller than the "hushed face" PNG Twemoji, see:

https://github.com/twitter/twemoji/blob/gh-pages/72x72/1f62f.png

It's easily noticeable when opening both faces in separate tabs and switching between both tabs for example (using Mozilla Firefox 37.0.1).

And those two Emojis are just one example.

**Comment by WebReflection** [comment]
> I don't really know what you mean
that library is vulnerable to XSS and script injection due poor HTML escaping/unescaping, it's not about being kind or anything, it's a concrete security concern and I've filed a bug there.

Rephrasing: oh wow, are you guys aware your sites can be exposed to a security problem exposed by that library?

Not sure that sounds any kinder but until they fix you rather be aware of this.

About different sizes, yeah, I've kinda noticed too but never before since I've never used such big emoji.
As example, I don't see big difference here: http://twitter.github.io/twemoji/preview.html

But yeah, using 72x72 assets seems to make it evident but I've no idea if any designer here (I'm not, I take care of the JS library) would go and fix 800 images in order to make them exactly as big, also I see some image has decorations around that would make it hard to have perfect/exact match.

I'll flag this as improvement and wait for a designer to eventually chime in and resolve or improve.

**Comment by pento** [comment]
Funnily enough, we just discovered the [same sizing problem](https://core.trac.wordpress.org/ticket/31709#comment:9) when working on the WordPress implementation of Twemoji.

We don't have a solution yet, but we're thinking about it. :-)

**Comment by WebReflection** [comment]
hi @pento ... just one note about this

> The SVG output code is also a bit messy: 

the output is generated automatically, and it actually works better than manually exported from AI (few cases were breaking there)

If you folks have a better suggestion for [settings I'm using here](https://github.com/twitter/twemoji/blob/gh-pages/svg.sh) I'm listening

**Comment by WebReflection** [comment]
P.S. please note those settings were necessary in order to avoid sizing problems in IE9 and others

**Comment by pento** [comment]
Thanks for the extra info, @WebReflection! I'll let you know what we come up with, we'll see if we can make it work for you, too. 😀

**Comment by wp9015362** [comment]
> @pento wrote:
> 
> Funnily enough, we just discovered the [same sizing problem](https://core.trac.wordpress.org/ticket/31709#comment:9)
> when working on the WordPress implementation of Twemoji.

Ah, maybe you should add a link to this issue here then, so that the others from your issue tracker know that the issue is also being addressed on the official Twemoji issue tracker :wink:?

> @WebReflection wrote:
> 
> About different sizes, yeah, I've kinda noticed too but never before since I've never used such big emoji.
> As example, I don't see big difference here: http://twitter.github.io/twemoji/preview.html

The size inconsistency is definitely noticeable there as well (for me at least).

> @WebReflection wrote:
> 
> but I've no idea if any designer here (I'm not, I take care of the JS library) would go and
> fix 800 images in order to make them exactly as big, also I see some image has
> decorations around that would make it hard to have perfect/exact match.

Well, I don't know how much work it would be to do this, but I think it should be done nevertheless, as it can look quite buggy.

And while the designer would be at it, it would be nice if he would also [give the Twemojis a faint, narrow contrasting border to keep them visually distinct from a similarly colored background (as recommended by latest Draft Unicode Technical Report 51)](https://github.com/twitter/twemoji/issues/62).

> @WebReflection wrote:
> 
> I'll flag this as improvement and wait for a designer to eventually chime in and resolve or improve.

I don't think this should be flagged as an improvement, but rather as a bug.

Also, with "waitining for a designer to eventually chime in" do you literally mean waiting on a designer  to eventually chime in?

Or are you going to pro-actively contacting a designer and making him aware of this issue?

> @pento wrote:
> 
> I'll let you know what we come up with, we'll see if we can make it work for you, too.

Thank you very much in advance.

Regards

**Comment by WebReflection** [comment]
> Or are you going to pro-actively contacting a designer and making him aware of this issue?

I don't even work at Twitter anymore and I don't know who is in charge. I take care of the JS side of the project and eventually I send emails to the project owner, that's pretty much it.

**Comment by wp9015362** [comment]
> @WebReflection wrote:
>
> I don't even work at Twitter anymore

Ah, the [README.md](https://github.com/twitter/twemoji/blob/gh-pages/README.md) still says:

> [...] Committers and Contributors
>
> Andrea Giammarchi (Twitter) [...]

:wink:

> @WebReflection wrote:
>
> and I don't know who is in charge.

So, is there any way we can find out who is in charge?

> @WebReflection wrote:
>
> I take care of the JS side of the project and eventually
> I send emails to the project owner, that's pretty much it.

Who is the owner?

**Comment by WebReflection** [comment]
I've just pushed the clarification about me ... now I'm (ex-Twitter) while the main person behind this is, AFAIK, @caniszczyk but he's not a designer neither. Now he's mentioned at least, let's see if he'll tell us more.

**Comment by wp9015362** [comment]
Thanks for the info.

@caniszczyk :

Can you please clarify the maintenance situation for the Twitter "Twemoji" Emoji set and forward this issue (and ideally [all the others](https://github.com/twitter/twemoji/issues)) to the proper maintainer/owner/designer?

It would be much appreciated.

Regards

**Comment by caniszczyk** [comment]
I'll investigate internally.

**Comment by jasmussen** [comment]
Based on [the github export document](https://github.com/twitter/twemoji/blob/gh-pages/svg.sh), it seems as though there's a single .ai file per emoji, meaning 800+ .ai files in a folder, and I'm assuming those individual .ai files aren't exported from yet another master document.

Looking at [http://twitter.github.io/twemoji/preview.html](this preview page), (which reveals sizing issues when you zoom in) it becomes clear that the vast majority of the set has no issues to speak of. **It seems sizing issues are limited to the "yellow face emoji", of which I counted a total of 65**. So already there it drastically reduces the amount of work to be done.

Out of those 65, it seems like **most** of those yellow face emoji have a head size of `21,474px`. Some of those are shifted downwards vertically, and some are bigger, but if we just decide that `21,474px` vertically centered is the canonical size and position, then I'll bet we're only looking at a 4th of the original 65 .ai files with problems needing fixes.

That's not too much work. If I had access to those 65 .ai files, I could probably churn that out for you relatively quickly and submit it back upstream.

**Comment by WebReflection** [comment]
> If I had access to those 65 .ai files, I could probably churn that out for you relatively quickly and submit it back upstream.

Not sure I understand ... you could fork, grab all .ai and send a PR back, right? Or there's something else blocking a possible PR?

My problem is that I don't have AI at all and not planning to have one any time soon, but I can convert through Inkscape locally and see at least how it looks [as SVG](http://twitter.github.io/twemoji/preview-svg.html)

If that works, we can think on how to export those modified AI as PNG of various size. I remember designers did some work there too for optimal 16x16 settings VS 72x72 one

**Comment by jasmussen** [comment]
> Not sure I understand ... you could fork, grab all .ai and send a PR back, right? Or there's something else blocking a possible PR?

Doh, didn't notice that the .ai files *are* indeed part of this repo! Sorry about that.

> If that works, we can think on how to export those modified AI as PNG of various size. I remember designers did some work there too for optimal 16x16 settings VS 72x72 one

I'll take a look at unifying the buggy ones in 72x72px first, as it's most noticable there, then I can take a look at the other sizes later, see how the situation is.

**Comment by WebReflection** [comment]
Thank you!

**Comment by wp9015362** [comment]
@WebReflection & @caniszczyk :

Now that @jasmussen has fixed the size inconsistencies, I am wondering:

When will the changes/updates made in this Twemoji repository actually show up on Twitter?

Is this Twemoji repository somehow directly connected to Twitter so that Twitter will automatically pick up the updates made in the Twemoji repository?

Or how does this work?

What needs to be done so that the changes will actually show up on Twitter?

Regards

**Comment by WebReflection** [comment]
Somebody needs to export changed icons PNGs for all 3 sizes, then MaxCDN will purge edge cache and slowly everybody will download those changed in their cache. This, assuming they use MaxCDN, but once we have all assets I know who to bother for updates on Twitter or TweetDeck side, that's the easy part. Before that, we need PNGs too

**Comment by jnievelt** [comment]
@WebReflection that sounds correct for existing emoji.  If we add new emoji, there is some internal code that needs to be regenerated & deployed as well.

**Comment by WebReflection** [comment]
not for twemoji.js, the generator.js does that already ... but yeah, if you use server-side version I guess you do have to update that too.

**Comment by wp9015362** [comment]
> @WebReflection wrote:
> 
> Before that, we need PNGs too.

Any update?

And what about those:

https://github.com/twitter/twemoji/commit/d0e45fee1b7d2b5828de9d4e5c01acb84ef4a116

?

There also still don't seem to be any SVGs nor PNGs for them.

What's the impediment impediment regarding the PNGs and SVGs?

Also:

> @caniszczyk wrote:
> 
> I'll investigate internally.

Any update?

Regards

**Comment by WebReflection** [comment]
@wp9015362 you won't have graphical updates from me and the impediment is: I don't have AI and I'm not a designer. I can use common sense on a PR that exports and updates PNGs but I won't be the one pushing it. Feel free to contribute with one PR

**Comment by wp9015362** [comment]
Almost have a year later and still no update.

No offence, but:

Is this project dead?

Is Twitter still commited to Twemoji?

Regards

**Comment by waldyrious** [comment]
Would it be acceptable to have a script to generate pngs from the svg versions, like [svg.sh](https://github.com/twitter/twemoji/blob/gh-pages/svg.sh) does for converting the ai files to svg? Or are there special considerations/settings that need to be used when generating the pngs? I am willing to contribute a PR if I know what needs to be done :)

**Comment by WebReflection** [comment]
@waldyrious AFAIK pngs were hand crafted, in order to be sure that 16x16, as example, were looking fine. An automatic procedure won't probably grant same clear results.

For what I can tell, I haven't received any notification from twitter about one or more designers in charge of maintaining the visual quality of this repository, and while I am actually happy the JS side of the project never had a glitch or problematic bug reports so far, I cannot maintain the graphical part of it 'cause I'm not a designer.

I'd be quite bad to loose MaxCDN support for this project, which is mostly the reason I am not forking this repository, but since nobody is coming back with updates about this projects, all I can  say is that if the proposed PNGs look good to my non designer eyes, I'll accept the PR and re-generate the script accordingly.

The only thing I ask however would like to contribute, since I don't want to take any responsibility about it, is to use registered software whenever some asset gets created.

Last time I've asked for this, the person got upset ... but I'm not even an employer anymore, so I don't want to 'cause, or be the target, of any trouble.

Thanks to whoever would like to contribute keeping this repository updated.

**Comment by wp9015362** [comment]
Just saying:

Since Twitter doesn't seem to care about Twemoji (it would be nice to be proven wrong), maybe it would make more sense to contribute to the open source Emoji One project instead.

Emoji One is actively being maintained and Emoji One recently joined the Unicode Consortium, see:

http://emojione.com/blog/emoji-one-joins-unicode-consortium/

And Emoji One is currently developing a brand new Emoji set ("The 2016 Collection"), due to be released in November 2015, see the top of the following welcome page for a preview:

http://emojione.com/

Regards

**Comment by rodrigopolo** [comment]
@wp9015362 finally another SVG library! I was looking for something like that a long time ago for my project: https://github.com/rodrigopolo/minEmoji I'm going to see how can I contribute to Emoji One :grinning:

**Comment by WebReflection** [comment]
> maybe it would make more sense to contribute to the open source Emoji One project instead

well, this is an Open Source project too after all, not sure I follow your logic, but I surely won't stop you to adopt, use, or help emoji one, or any other project, neither.

It's so dumb there are so many projects around this topic, Mozilla also hired an external designers to do their own, we could have all merged the effort instead :-(

**Comment by rodrigopolo** [comment]
I created a fork from this project and then I added all of the diversity emojis, and many others in Unicode 8, the fork is here:
https://github.com/rodrigopolo/twemoji

You can review each one of the additions here:
http://rodrigopolo.com/files/emojilist/

I really want to contribute, but contribution work both ways and I see this project hasn't been active for some time and I saw no interest in my contributions, Emoji One looks interesting now.

**Comment by WebReflection** [comment]
I understand @rodrigopolo but I'm afraid there's not much I can personally do. Let's hope there will be some update in here ... **soon**

**Comment by waldyrious** [comment]
> use registered software whenever some asset gets created, modified, and PR'ed

As opposed to what -- pirated, or something? I was planning on using open-source software (Inkscape), so would that sidestep the issue? In fact it would be great to eliminate this repo's dependence in .ai files since svg should fit their role pretty well and it's an open format. Is that a possibility?

> Thanks to whoever would like to contribute keeping this repository updated.

I am glad you're around, responsive, and willing to merge PRs :) That's already more than many FOSS projects in github, unfortunately.

> Since Twitter doesn't seem to care about Twemoji (it would be nice to be proven wrong), maybe it would make more sense to contribute to the open source Emoji One project instead.

If that's the case I'd be tempted to propose some stylistic changes which have always bothered me, since they seem to have been implemented solely to match Apple's style, which other popular packs have fortunately avoided. For example, the weird mouth of the "grimacing face" ([U+1F62C](http://unicode.org/emoji/charts/full-emoji-list.html#1f62c)) and the "grinning face with smiling eyes" ([U+1F601](http://unicode.org/emoji/charts/full-emoji-list.html#1f601)), the open eye of "face with stuck-out tongue and winking eye" ([U+1F61C](http://unicode.org/emoji/charts/full-emoji-list.html#1f61c)), and the unnecessary blushing in "white smiling face" ([U+263A](http://unicode.org/emoji/charts/full-emoji-list.html#263a)), "smiling face with smiling eyes" ([U+1F60A](http://unicode.org/emoji/charts/full-emoji-list.html#1f60a)), and perhaps even "kissing face with closed eyes" ([U+1F61A](http://unicode.org/emoji/charts/full-emoji-list.html#1f61a)), since, despite being more fitting there, it undermines more innocuous uses of the emoji. Note that there's a specific "flushed face" emoji ([U+1F633](http://unicode.org/emoji/charts/full-emoji-list.html#1f633)). @WebReflection would you consider such changes?

> maybe it would make more sense to contribute to the open source Emoji One project instead.

Perhaps, but if PRs to this repo are indeed merged, I don't see the issue. Emoji One is great but they seem to be unwilling to deviate from the big ones even when it makes sense (e.g. https://github.com/Ranks/emojione/issues/50).

> It's so dumb there are so many projects around this topic, Mozilla also hired an external designers to do their own, we could have all merged the effort instead :-(

Yes, that bothers me a lot as well. It is important to keep these projects inclusive and open to contributions if we want people to join in, though, and some of the comments above seem to indicate the team behind Twemoji hasn't been very responsive in the past, so there's that. Again, if we can get changes merged and the project moving forward, there's nothing stopping more widespread adoption, in principle.

> Let's hope there will be some update in here ... soon

So... if @rodrigopolo submits his changes as a PR will they be merged? Otherwise, what is the update we're hoping for?

**Comment by wp9015362** [comment]
> @waldyrious wrote:
> 
> Emoji One is great but they seem to be unwilling to deviate from the big ones even when it makes sense (e.g. Ranks/emojione#50).

Actually that is for good reason and very welcome IMHO. If they would not do that, then the Emojis could easily get lost in translation as described in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

Which would suck.

Anyway, [Emoji One has now joined the Unicode Consortium](http://emojione.com/blog/emoji-one-joins-unicode-consortium/) and they are now developing an entirely new Emoji set from the ground up, "The 2016 Collection", which is scheduled to be released in November 2015.

As you can see from the preview on the welcome page and on the Instagram account:

http://emojione.com/
https://instagram.com/emojione/

it seems like the new Emoji set will look rather different compared to the Apple set.

Just yesterday I actually have already asked them if it's no longer a design goal of them to look similar to the Apple set, see:

https://github.com/Ranks/emojione/issues/126

But they haven't anwered yet as you can see.

> @rodrigopolo wrote:
> 
> I'm going to see how can I contribute to Emoji One

To be fair, there doesn't seem to be much that could to be done (at least at the moment), since their current Emoji set (version 1.5) already is fully Unicode 7.0 compatible (including middle finger Emoji and so on) and they are also working on the skin tone modifier feature, see:

https://twitter.com/emojione/status/635840522712653824

And on top of that, they are currently developing a brand new Emoji set, which is scheduled to be released in November 2015 (see above) and which (hopefully) will also bring full Unicode 8.0 support.

So, Emoji One is already way ahead of Twemoji.

> @WebReflection wrote:
> 
> It's so dumb there are so many projects around this topic, Mozilla also hired an external designers to do their own, we could have all merged the effort instead :-(

Sorry, but Emoji One was actually first. Emoji One was there before Twitter released (open sourced) Twemoji, see:

http://emojione.com/blog/congrats-twitter-from-emoji-one/

And, apart from that, Twitter didn't even design Twemoji on their own. They hired an external company (The Iconfactory) to do it for them, see:

http://design.iconfactory.com/twitter-emoji/

So, Twitter could have contributed to Emoji One, not the other way around :yum: .

Regards

**Comment by WebReflection** [comment]
@waldyrious 

> As opposed to what -- pirated, or something? I was planning on using open-source software (Inkscape)

I don't have Illustrator neither, that's why I can't even test files someone might PR unless I use Inkscape to see the resulting SVG. Unfortunately this entire repo was born after AI files, and all utilities around use them to create SVG and check sources, etc etc.

So, to answer your question, if you push a SVG is fine but also pointless 'cause we need the AI one. If you have an OS software that generates AI then it's OK, we should probably mention it in this repo, and we should simply accept PRs with files generated from it. Does such software exist? I thought Inkscape could convert or import them, but not create .ai files ... am I wrong?


@wp9015362 

> Sorry, but Emoji One was actually first ... etc etc ...

where exactly did you read I've said twemoji was first? which part of "_we could have all merged the effort instead_" excludes in your mind this project from the list of possible contributors, or proclaims its originality and legacy regarding this matter?

There's no need to fight any war here, it's actually the opposite so feel free to write "fanboy" style comments whenever you want but maybe not here, thank you, yeah?!



**anyway**
I'm tempted to check emoji one repo and eventually fork them and this one, bringing same JS API on top of their assets or simply PR them a similar one.
If they are active even with the consortium and they are actively maintaining their project maybe it's not too late to join "our" effort and move on with this.

**Comment by waldyrious** [comment]
> I thought Inkscape could convert or import them, but not create .ai files ... am I wrong?

That's my understanding as well, hence my question on whether moving away from .ai files could be a viable goal for this project. It is rather unfitting (self-defeating, really) for an open source project to depend on a closed format that requires commercial, closed-source software to manipulate. Do you think moving to svg as the canonical sources would make sense? I would be willing to help in whatever tasks are required for such a conversion. I'm quite used to hand-editing svg files, so I could for instance retouch them to fix any issues than an automatic conversion might produce.

> maybe it's not too late to join "our" effort and move on with this.

That sounds great, but the question of stylistic harmonization comes into play again (please refer to my previous comment above for details). Do you have any thoughts on that?

**Comment by jasmussen** [comment]
> That sounds great, but the question of stylistic harmonization comes into play again (please refer to my previous comment above for details). Do you have any thoughts on that?

I generally am a big fan of what The Icon Factory has done with the visual expression of this entire set. But here and there, there are legitimate issues that are worth fixing. We've already fixed a few things, like harmonizing the sizes of some of the yellow-face emoji, and add or remove a tear here and there. But it's probably worth discussing issues such as that in separate individual tickets, so suggestions can be discussed and evaluated on a case by case basis.

**Comment by WebReflection** [comment]
> Do you think moving to svg as the canonical sources would make sense?

here it's a matter of original assets and the license behind ... the TL;DR of my answer is: I don't know if that would make sense in this repo based on those assets.

**Comment by waldyrious** [comment]
Fair enough, I guess those can be dealt with individually. Still, I wonder how you're envisioning a merging of efforts. Would the design language of Twemoji be abandoned in favor of Emoji One's? Do you foresee any integration otherwise (e.g. meeting halfway)?

And sorry to insist, but can you guys comment on the viability of moving to svg assets as primary sources for Twemoji rather than .ai files?

**Comment by jasmussen** [comment]
> Still, I wonder how you're envisioning a merging of efforts. Would the design language of Twemoji be abandoned in favor of Emoji One's? Do you foresee any integration otherwise (e.g. meeting halfway)?

We're all just casual contributors. In absence of commentary from the creators, we can only just give opinions and thoughts. Here's my opinion.

I love Emoji One. I think it's a fantastic project. Creating an entire complete Unicode 8 emoji set from scratch is a *massive* undertaking. I also like their artstyle, which I consider very different from the more all-flat, in some ways "stylized" approach that Twemoji has. I think the two can and should co-exist, so people who need an open source set of emoji can pick one or the other. One true set doesn't have to "win", and it wouldn't be able to. Windows 10 has a set, OS X has a set, Google has a set, and now open source offers multiple sets. It's like fonts: there isn't one true font you'll use for everything.

That's not to say there can't be cross-pollination; one set can learn from other sets lessons, and so on. 

I'd even go so far as to say that icons contributed to one set can be contributed to another, but I would add to that they would have to be changed to fit the visual style of the set it was contributed to. 

> And sorry to insist, but can you guys comment on the viability of moving to svg assets as primary sources for Twemoji rather than .ai files?

Again, I'm just a contributor offering opinions: SVGs are wonderful. But they are fragile. One illustration app will save vector coordinates in unlimited decimal places, another will round up to the nearest 4th decimal place. In that sense, SVG can be a destructive format depending on the app that saves it. So I would think it a mistake to actually delete or deprecate .AI files as a means of contribution. In fact I'd rather like to see that SVG is the *destination* file format, and you can contribute your vector graphics in any source format you like (even SVG!). The key is that we end up having SVGs to evaluate, and run scripts on to generate PNGs and whatnot. In other words, you can contribute SVGs and .AI files, or just SVGs, or SVGs and PDFs, or SVGs and EPSs. I personally see no reason to be picky, source files are yummy :)

**Comment by WebReflection** [comment]
well, not here, we want consistency across platforms. As example, SVG must be available as PNG in all supported formats.

If the problem is that many software could save SVG differently, we have an easy solution: Inkscape MUST be the exporter for the SVG, as it is already now. This not only grants similar SVGs, it has been already demonstrated Inkscape exports SVG even better than AI in some case, and it's widely copatible, after the automated fix about the viewbox, with most browsers.

So SVG is not an option, is the most welcome final target, also because today 90% and more of browsers support already SVG, there's no reason to go PNG if not in certain edge cases.

I agree emoji are like fonts, every OS will have its own because they want to differ, same as every OS will have its own UI and stuff ... but the point of having **one set** for the Web is to indeed align surfers and avoid misunderstanding.

Emoji are indeed like fonts, if I write Y nobody should read N instead ... this is the main bummer about the current status. Me in the first place complained about the moon that should be grey but in most sets it's not, and it doesn't matter if I am wrong or right, as long as everyone understand it's a moon. So if yellow works, yellow it is.

I've personally asked around to my contacts about the current situation, and nothing is clear yet.
I had a look at the Emoji One already and they do "funny things" escaping RegExp and creating both the huge RegExp and an even biger Object instead of runtime replacement, I don't think they would mind having a JS converter which is half size and twice as fast, with a simple API that so far worked quite well.

I'll try to fork them whenever I have time and see if I can build same JS on top.
Once again, I'm the JS maintainer here, and that's the part I can change ... since I want to use updated emoji as well, and since this API worked already for "millions", I might just bring it there and see if they'll welcome it or not. In either cases, I'll have a repo based on assets that will be updated for sure.

I will keep you updated here. Cheers

**Comment by waldyrious** [comment]
@jasmussen very sensible stance on the cooperation issue with Emoji One, I fully agree. As for SVG vs. AI, what you point out is actually *less* of an issue with SVG, since it is a plaintext format, so git is able to both store it efficiently, and deal with changes in a more semantic way rather than as a bulk binary blob change. That is, any change will be viewable as a diff, and changes in precision can thus be easily identified, even by automated tools (we can make tests to be run by Travis on every PR to prevent that precision reduction issue, for instance). Even visual changes can be more easily seen in diffs, since github is able to render them inline (again, because it is an open format).

@WebReflection, you say

> So SVG is not an option

Can you clarify why you say that? It wasn't clear for me.

**Comment by jasmussen** [comment]
One quick addition, in the case of SVG vs. AI, any day of the week I will defer to WebReflection on what should be the process here. He's actually worked on the scripts and used them, he has a perspective I don't have. I'm mainly a graphic designer.

**Comment by WebReflection** [comment]
@waldyrious 

> (we can make tests to be run by Travis on every PR to prevent that precision reduction issue, for instance)

no we can't. For instance,  the viewbox hard fix is necessary because IE9 Mobile and some Black Berry won't otherwise show them correctly. TL;DR every single SVG emoji has been [tested through this page](http://twitter.github.io/twemoji/preview-svg.html) in every target platform,  something Travis is unable to do. Developers often  forget that  Web !== ChromeDriver || PhantomJS, specially on Mobile there's still, unfortunately, some idiot (here I am) that tests things for real on real devices ('cause again simulators lie). But trust me ... I wish it was that easy to automate real graphic results!

> Can you clarify why you say that? It wasn't clear for me.

When I've said SVG is not an option,  I meant because it's *mandatory* target. If this could also be the source, and we can be sure as source is consistent (we all use the same software) then I don't see any problem. But again, nobody here holds design/graphic copyrights, so switching to SVG as primary assets source should be agreed from others maintainers too.

Then we have the little problem that this repo is also aligned with MaxCDN so that we probably cannot get rid of the AI folder anyway without causing some undesired side effect.

oh well ... "the Web is fun"

**Comment by waldyrious** [comment]
Thanks for the details. Let me know if I got it right: so the .ai files are the canonical sources, the svg are generated from the .ai files, but need to be manually checked so that platform-specific rendering issues don't occur. We *could* move to svg as the source material (as well as one of the final asset formats) but we would need to ensure that any change they remain consistent across platforms. Is that right?

If so, how is that proposed workflow different from the current one, i.e. making sure that any change to the .ai assets (or new .ai assets added) produces svg output that is consistent with the remaining assets and across platforms? It seems like the verification work is necessary either way, so .AI is just adding an extra step here, and one that makes it harder for people to contribute.

The README says "Graphics licensed under CC-BY 4.0", so I see no issue with creating derivative works out of them, especially since the only thing that would change is the representation format (ai to svg), not the actual design.

**Comment by kristyheger** [comment]
Not sure what any of this means as I am just learning

**Comment by WebReflection** [comment]
@waldyrious AI are a consistent input from which Inkscape can generate a consistent output that I can automatically patch. The big job of checking all assets has been done already, I eventually check only new emoji or those modified through that page. Most of this repo is based on some automation and if you think we can just ignore AI and use SVG I'd say why not, but there are things to change.

I find it quite weird nobody is officially commenting on any of this ... it's one bummer blocking me to proceed in a way or another (this plus the fact I don't have much time these days)

Let's hope for some "signal" from other maintainers.

**Comment by waldyrious** [comment]
> Most of this repo is based on some automation and if you think we can just ignore AI and use SVG...

Just to be clear, I am fully on-board with @jasmussen in deferring to your experience and know-how regarding what approaches are feasible or reasonable. I'm just raising questions to better understand how I can help this project move forward.

I am assuming (and please correct me if I'm wrong) that if all the .ai files have already been converted to svg and verified to be visually identical, then we could switch to using svgs as the source material without any effect on the visual output.

> ...I'd say why not, but there are things to change.

I understand there are scripts and processes in place that assume .ai assets, and I'm willing to contribute whatever is within my reach to help port them to deal with svg files. I don't have a lot of experience but I am willing to learn. Particularly, if there are simple stuff that may be cumbersome or time-consuming, I would be willing to lend my time and patience :)

> I find it quite weird nobody is officially commenting on any of this ... it's one bummer blocking me to proceed in a way or another (this plus the fact I don't have much time these days). Let's hope for some "signal" from other maintainers.

That's unfortunate indeed. I'll stay tuned to any developments.

**Comment by WebReflection** [comment]
unfortunately the automation is mostly done via quick and dirty bash scripts that just works ... I really don't think a designer should learn Bash so I'll think about what's needed and if there's anything non Bash I'll let you know :D

**Comment by wp9015362** [comment]
> @jasmussen wrote:
> 
> One true set doesn't have to "win"

I very much disagree. I can't refer to the following article often enough to give one simple reason why one set should win:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

> @jasmussen wrote:
> 
> and it wouldn't be able to.

Of course it won't be able to if there are people like you who don't believe in it...

> @jasmussen wrote:
> 
> Windows 10 has a set, OS X has a set, Google has a set, and now open source offers multiple sets. It's like fonts: there isn't one true font you'll use for everything.

The Google set is open source as well, see:

https://github.com/googlei18n/noto-emoji

:yum:

>  @WebReflection wrote:
> 
> I find it quite weird nobody is officially commenting on any of this ... it's one bummer blocking me to proceed in a way or another (this plus the fact I don't have much time these days)
> 
> Let's hope for some "signal" from other maintainers.

Sorry, but if your time is that limited, then why waste it hoping for a signal from Twitter, when there hasn't been any signal whatsoever for several months now?

Twitter seems to have abandoned Twemoji, so hope can be abandoned as well and the time could better be spent on Emoji One.

And let's face it Twemoji has nowhere near the quality of the upcoming new set from Emoji One, which can easily be seen when looking at their latest preview images on their Instagram account:

https://instagram.com/emojione/

And no, this is no fanboy talk, this is simply being realistic after having waited for a reply from Twitter for so long (and that even though @caniszczyk said he will investigate internally [half a year ago already](https://github.com/twitter/twemoji/issues/60#issuecomment-90937658)).

If they don't care, why should anyone else?

Yes, this is an open source project, but you yourself said it's difficult to go forward without them.

Regards

**Comment by wp9015362** [comment]
For the record:

Two days ago, @caniszczyk wrote in https://github.com/twitter/twemoji/issues/48:

> Just to give an update, this is something we're working on within Twitter.
> 
> Look for updates in the near future within twemoji!

Regards

**Comment by bhaggs** [comment]
These should all be corrected now as part Twemoji 2.0.
