### ISSUE TITLE
Please give Twemojis a faint, narrow contrasting border to keep them visually distinct from a similarly colored background (as recommended by latest Draft Unicode Technical Report #51)

### ISSUE THREAD

**Issue by wp9015362** [twitter/twemoji#62]
Hello,

the Twemojis do not have a faint, narrow contrasting border to keep them visually distinct from a similarly colored background.

The latest Draft Unicode Technical Report 51:

http://www.unicode.org/reports/tr51/

recommends to give Emojis a faint, narrow contrasting border to keep the them visually distinct from a similarly colored background.

Please give the Twemojis a faint, narrow contrasting border to keep them visually distinct from a similarly colored background.

Regards

**Comment by wp9015362** [comment]
PS:

It seems like Google also is doing this for their "Noto Color Emoji" Emoji set.

If you take a look at the updated Emojis shown over there:

http://blog.emojipedia.org/android-50-emoji-changelog

then you can see that all the updated Emojis now have a faint, narrow contrasting border around them to keep them visually distinct from a similarly colored background.

It would be really nice if you could do it for the Twitter "Twemoji" Emoji set as well.

**Comment by jasmussen** [comment]
I disagree that this should be adopted for Twemoji.

There are many different emoji sets one can pick from, each with their own distinct creative interpretation of the unicode rules. Adding borders to all emoji is a big creative revision to all existing emoji.

**Comment by WebReflection** [comment]
I don't know the amount of job required but I agree with @jasmussen here, this is a recommendation but not exactly a bug so I'll flag as feature request.

**Comment by wp9015362** [comment]
> @WebReflection wrote in https://github.com/twitter/twemoji/issues/38#issuecomment-90937589 :
> 
> Others might be different too, we all love variety, right ?

+

> @jasmussen wrote:
> 
> There are many different emoji sets one can pick from,
> each with their own distinct creative interpretation of the unicode rules.

Sorry, but I hate this argument.

Those "creative interpretations" lead to one big issue, which is that Emojis can get lost in translation between different devices / different platforms, as described in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

A recent example:

To my surprise I just discovered that Mozilla seems to have created yet another clompetely new Unicode 7.0 Emoji set, which apparently will be used for Firefox and Firefox OS, see:

http://www.sabrinasmelko.com/portfolio/emojis/

and:

https://bugzilla.mozilla.org/show_bug.cgi?id=1053216

This set seems to look quite nice, perhaps even better than the Twemoji set in some parts...

BUT:

Look what has happened due to the "creative interpretations"...

The faces in that set look like little babys, they even have ears and their expressions and their general looks are way different than most other Emoji sets.

And the cat faces in that set actually are fox faces...

IMHO it's really sad that most Emoji sets are different from each other in some ways and easily can get lost in translation...

Okay, to be fair, the fact that the Twemojis currently do not have a contrasting border around them probably does not increase the chance of them getting lost in translation, but, still, I think they should have one because the Twemojis do not have enough contrast on some backgrounds, even on a white background.

Regards

**Comment by WebReflection** [comment]
I see emoji as a browser select box: every single OS will render that differently but the usage and functionality is clear for everyone. We'll never have same iOS/OSX set unless they Open Source all their assets.

About Mozilla set ... https://twitter.com/webreflection/status/572811087785152513

I have no idea why they hired a person instead of contributing here ... and I've never had an answer to those questions.

**Comment by wp9015362** [comment]
> @WebReflection wrote:
> 
> every single OS will render that differently but the usage and functionality is clear for everyone.

I disagree. Just an example:

Take a look at the "crystal ball" Apple Emoji for example:

:crystal_ball: 

IMHO it can easily be recognized as a crystal ball.

But now take a look at the "crystal ball" Twemoji:

![Image](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/72x72/1f52e.png)

To me it doesn't look like a crystal ball at all. I really couldn't tell what it is supposed to be if I wouldn't know the description "crystal ball". And that really sucks (IMHO).

That's just one example.

> @WebReflection wrote:
> 
> I have no idea why they hired a person instead of contributing here ...

Well, upon comparing the date of this post:

https://bugzilla.mozilla.org/show_bug.cgi?id=1053216

with the date of this post:

https://blog.twitter.com/2014/open-sourcing-twitter-emoji-for-everyone

it seems like Mozilla designed their set before Twitter open sourced their set?

Regards

**Comment by jasmussen** [comment]
@wp9015362:

For better or worse, the visual style of Twemoji is flat and minimalistic and with very few outlines. This is a creative choice that's rather popular these days: just look at the Android and Windows system emoji sets, they also have very little flair.

Adhering to this style means that some emoji, such as the crystal ball, can perhaps be hard to interpret at a glance. This is a challenge that all avenues of graphic design have, including logo design, font design and pictogram design. For example, if you look at individual letters in the font Helvetica most of them will probably be easy to identify because that was one of the primary goals the designers had in mind when designing the font. But if you look at letters in a decorative cursive font such as [https://www.google.com/fonts/specimen/Clicker+Script](Clicker Script), it will be hard to identify the capital G at first glance. That doesn't mean the two fonts can't co-exist, it just means you probably don't want to set a street-sign in the cursive font :)

For that reason I believe emoji sets, just like fonts, should be allowed some creative wiggle-room. Are all the Twemoji perfectly legible? No, and you've submitted some good tickets suggestions for improvements: removing or moving a teardrop to make an emoji more legible can be done in a way that respects the overall visual style and vision laid out by The Icon Factory.

Adding a faint narrow stroke around all emoji so as to make sure they work on any background color, however, is a big visual change of direction for the entire set. It adds complexity and detail, and it takes away from the original minimalist vision for the set. Keeping in mind it's only a unicode recommendation, I would argue against adding outlines.

Remember, I'm just a volunteer here, and this is just my opinion. I help out because I'm just so gobsmacked and thankful that Twitter had 800+ emoji drawn (a monumental task) and then decided to give them away to open source.

**Comment by WebReflection** [comment]
> it seems like Mozilla designed their set before Twitter open sourced their set?

and since when opening a task means the task is complete?

True that we had an unfortunate overlap and at Twitter we should have released them earlier since these have been around in twitter.com for quite a while.

But once we released, instead of merging effort, [they decided to complete the task anyway](https://bugzilla.mozilla.org/show_bug.cgi?id=1053216#c4).

Again, it's a very good job from Sabrina Smelko, but that's the graphic part, what I am also complaining is that they had nobody assigned for the JS side and I can bet whatever you want they assigned such task instead of recycling or contributing with this project.

This "we want everything in-house made" from corporates, specially those that officially embrace Open Source, is something beyond my understanding. Everything ends up on "so we can have control over this" which is IMO not exactly what Open Source is about.

Best Regards

P.S. in case it wasn't clear already, I'm a volunteer too

**Comment by wp9015362** [comment]
> @jasmussen wrote:
> 
> For better or worse, the visual style of Twemoji is flat and minimalistic and with very few outlines. This is a creative choice that's rather popular these days: just look at the Android and Windows system emoji sets, they also have very little flair.

The Google "Noto Color Emoji" Emoji set and the Microsoft "Segoe UI Emoji" Emoji set seem to be the least popular though, so...

> @jasmussen wrote:
> 
> Adhering to this style means that some emoji, such as the crystal ball, can perhaps be hard to interpret at a glance. This is a challenge that all avenues of graphic design have, including logo design, font design and pictogram design. For example, if you look at individual letters in the font Helvetica most of them will probably be easy to identify because that was one of the primary goals the designers had in mind when designing the font. But if you look at letters in a decorative cursive font such as Clicker Script, it will be hard to identify the capital G at first glance. That doesn't mean the two fonts can't co-exist, it just means you probably don't want to set a street-sign in the cursive font :)

That's a poor comparison IMHO. A font can be hard to read, yes. But if one can read it, then one knows the exact meaning of the words written with it. There's no room for different interpretations. Either one can read it or not.

With Emojis, or with pictures in general, it is different. Pictures leave room for interpretation. They can be misinterpreted / misunderstood.

So, I think the comparison with regular fonts / letters is rather flawed.

> @WebReflection wrote:
> 
> which is IMO not exactly what Open Source is about.

Apparently she tweeted about it again a few hours ago and someone asked about the sources again, see:

https://twitter.com/SabrinaSmelko/status/586274190430511105

Still no answer so far...

Regards

**Comment by wp9015362** [comment]
> @wp9015362 wrote:
> 
> It seems like Google also is doing this for their "Noto Color Emoji" Emoji set.

> If you take a look at the updated Emojis shown over there:

> http://blog.emojipedia.org/android-50-emoji-changelog

> then you can see that all the updated Emojis now seem to have a faint, narrow contrasting border around them to keep them visually distinct from a similarly colored background.

This probably needs to be rectified.

The borders which can be seen on the Emojis over there:

http://blog.emojipedia.org/android-50-emoji-changelog

actually seem to come from a dark background. Maybe the Emojis simply were quickly cut out from a screenshot which had the Emojis shown on an Android keyboard with a dark background.

Because those borders do not seem to appear anywhere else, only in this blog post.

If you take a look at the following page:

http://www.unicode.org/Public/emoji/1.0/full-emoji-list.html

then you will see that the Google Emojis do not have such a border.

So, please ignore [the previous post](https://github.com/twitter/twemoji/issues/62#issuecomment-90897135).

Still would be nice though if the Twemojis would get a faint, narrow contrasting border to keep them visually distinct from a similarly colored background.

Regards

**Comment by rodrigopolo** [comment]
I have created a library which depends on SVGs from this library and I have upgraded the library to support the latest unicode emojis that are already available on iOS8.3 but I can't find many new emojis on this library.

Here is the project:
https://github.com/rodrigopolo/minEmoji

I'm currently using all PNGs I found on the Apple font in this versions:
http://rodrigopolo.github.io/minEmoji/jMinEmoji2/demo.html
http://rodrigopolo.github.io/minEmoji/minEmoji_iOS8/demo.html

So, anyone know when new pictures will be available?

Thanks!

**Comment by WebReflection** [comment]
3 identical posts ... @rodrigopolo please do not use opened bugs to promote your library. I am going to remove all of your 3 posts. Eventually feel free to ask a question in one place, or open a new bug. Thank you

**Comment by rodrigopolo** [comment]
@WebReflection I'm not promoting anything, I just increasing the probabilities of getting an answer, I was about to open a request (bug) asking for this new emojis but then I found there were 3 bug reports that essentially ask for the same thing (I'll consider merging them if you ask me), so, I'm not earning money nor "internet points", I'm not trolling or doing something bad to some one, just looking for some SVGs to do what exactly people need. I'll share the URL again NOT to promote but to get anyone interested into seeing that it is a real working library:
https://github.com/rodrigopolo/minEmoji

**Comment by kq01526** [comment]
Microsoft has done this now for their Emojis, see:

https://blogs.windows.com/windowsexperience/2016/04/06/announcing-windows-10-insider-preview-build-14316/

Looking very good.

**Comment by zilions** [comment]
Just do this with CSS and `box-shadow`, like so:

```
.twemoji {
    filter: drop-shadow(2px 2px 0 #000) 
            drop-shadow(-2px 2px 0 #000) 
            drop-shadow(2px -2px 0 #000) 
            drop-shadow(-2px -2px 0 #000);
}
```

Working example: https://jsfiddle.net/gdp5gctz/1/

**Comment by jdecked** [comment]
We won't be changing this right now. As a workaround for the moment, you can use the CSS solution commented above.

**Comment by rodrigoalcarazdelaosa** [comment]
Just for the record, I'm using [Twemoji](https://github.com/jakejarvis/hugo-mod-twemoji) in [my website](https://rodrigoalcarazdelaosa.me/en/) published with [Wowchemy](https://wowchemy.com/) and I also find many of the emojis hard to distinguish from the background. I'll try the [CSS trick](https://github.com/twitter/twemoji/issues/62#issuecomment-290631542) but would appreciate if this could be improved somehow in the future. Thanks in advance!

**Comment by rodrigoalcarazdelaosa** [comment]
> We won't be changing this right now. As a workaround for the moment, you can use the CSS solution commented above.

That CSS solution may work for some emojis but for others is _horrible_. Creative freedom is nice, but emojis serve a communication purpose, so they should adhere to some minimal accessibility restrictions such as having a good contrast against both light and dark backgrounds. My 2 cents.
